.ifndef BOSS2_INC
BOSS2_INC = 1

.include "spritesheet1.inc"
.import boss2_sprite_groups
.import boss2_palette
.import boss2_cycling_palettes
.import boss2_map
.import boss2_map_column_table
.import boss2_attribute_column_table
.import boss2_meta_tile_column_table
.import boss2_meta_tile_table
.import boss2_music

boss2_bank = 3

boss2_sprites_Nomolos_chr_index = 0
boss2_sprites_Thoguth_chr_index = boss2_sprites_Nomolos_chr_index+Nomolos_chr_size

.endif
