.ifndef boss5_INC
boss5_INC = 1

.include "spritesheet1.inc"
.import boss5_sprite_groups
.import boss5_patterns
.import boss5_palette
.import boss5_cycling_palettes
.import boss5_map
.import boss5_map_column_table
.import boss5_attribute_column_table
.import boss5_meta_tile_column_table
.import boss5_meta_tile_table
.import boss5_music

boss_5_bank = 5
boss_5_patterns_bank = 9

.endif
