.ifndef LEVEL2_2_INC
LEVEL2_2_INC = 1

level2_2bank = 1
level2_2patterns_bank = 8

.include "spritesheet1.inc"
.import level2_2patterns
.import level2_2palette
.import level2_2cycling_palettes
.import level2_2map
.import level2_2map_column_table
.import level2_2attribute_column_table
.import level2_2meta_tile_column_table
.import level2_2meta_tile_table
.import level2_2music

.endif
