.ifndef LEVEL2_INC
LEVEL2_INC = 1

level_2_bank = 1
level_2_patterns_bank = 8

.include "spritesheet1.inc"
.import level2_sprite_groups
.import level2_patterns
.import level2_palette
.import level2_cycling_palettes
.import level2_map
.import level2_map_column_table
.import level2_attribute_column_table
.import level2_meta_tile_column_table
.import level2_meta_tile_table
.import level2_music

.endif
