.ifndef LEVEL5_INC
LEVEL5_INC = 1

.import level5_patterns
.import level5_sprite_groups
.import level5_music
.import level5_meta_tile_table
.import level5_meta_tile_column_table
.import level5_attribute_column_table
.import level5_map_column_table
.import level5_map
.import level5_palette

level_5_bank = 4
level_5_patterns_bank = 9

level5_sprites_Nomolos_chr_index = 0
level5_sprites_statue_chr_index = level5_sprites_Nomolos_chr_index+Nomolos_chr_size

.endif
