.ifndef LEVEL4_INC
LEVEL4_INC = 1

level_4_bank = 3
level_4_patterns_bank = 9

.include "spritesheet1.inc"
.import level4_sprite_groups
.import level4_patterns
.import level4_palette
.import level4_cycling_palettes
.import level4_map
.import level4_map_column_table
.import level4_attribute_column_table
.import level4_meta_tile_column_table
.import level4_meta_tile_table
.import level4_music

.endif
