.ifndef LEVEL2_2BONUS_INC
LEVEL2_2BONUS_INC = 1

level2_2bonusbank = 15
level2_2bonuspatterns_bank = 8

.include "spritesheet1.inc"
.import level2_2bonusmusic
.import level2_2bonuspatterns
.import level2_2bonuspalette
.import level2_2bonuscycling_palettes
.import level2_2bonusmap
.import level2_2bonusmap_column_table
.import level2_2bonusattribute_column_table
.import level2_2bonusmeta_tile_column_table
.import level2_2bonusmeta_tile_table

.endif
