.ifndef LEVEL3_INC
LEVEL3_INC = 1

level_3_bank = 2
level_3_patterns_bank = 8

.include "spritesheet1.inc"
.import level3_sprite_groups
.import level3_patterns
.import level3_palette
.import level3_cycling_palettes
.import level3_map
.import level3_map_column_table
.import level3_attribute_column_table
.import level3_meta_tile_column_table
.import level3_meta_tile_table
.import level3_music

.endif
