;Animations
.export spritesheet2_NomolosWalk
spritesheet2_NomolosWalk:
  .byte $06
  .word spritesheet2_NomolosWalk0
  .word spritesheet2_NomolosWalk1
  .word spritesheet2_NomolosWalk0
  .word spritesheet2_NomolosWalk2
  .word $0000

.export spritesheet2_NomolosJump
spritesheet2_NomolosJump:
  .byte $0a
  .word spritesheet2_NomolosJump0
  .word $0000

.export spritesheet2_NomolosWalkOverlay
spritesheet2_NomolosWalkOverlay:
  .byte $0a
  .word spritesheet2_NomolosWalkOverlay0
  .word spritesheet2_NomolosWalkOverlay1
  .word spritesheet2_NomolosWalkOverlay0
  .word spritesheet2_NomolosWalkOverlay2
  .word $0000

.export spritesheet2_NomolosJumpOverlay
spritesheet2_NomolosJumpOverlay:
  .byte $0a
  .word spritesheet2_NomolosJumpOverlay0
  .word $0000

.export spritesheet2_Heart
spritesheet2_Heart:
  .byte $0a
  .word spritesheet2_Heart0
  .word $0000

.export spritesheet2_DeentleWalk
spritesheet2_DeentleWalk:
  .byte $0a
  .word spritesheet2_Deentle0
  .word spritesheet2_Deentle1
  .word $0000

.export spritesheet2_Explosion
spritesheet2_Explosion:
  .byte $02
  .word spritesheet2_Explosion0
  .word spritesheet2_Explosion1
  .word spritesheet2_Explosion2
  .word $0000

.export spritesheet2_Mouse
spritesheet2_Mouse:
  .byte $0a
  .word spritesheet2_Mouse0
  .word $0000

.export spritesheet2_NomolosFight
spritesheet2_NomolosFight:
  .byte $06
  .word spritesheet2_NomolosFight0
  .word spritesheet2_NomolosFight1
  .word $0000

.export spritesheet2_NomolosFightOverlay
spritesheet2_NomolosFightOverlay:
  .byte $06
  .word spritesheet2_NomolosFightOverlay0
  .word spritesheet2_NomolosFightOverlay1
  .word $0000

.export spritesheet2_NomolosUseFlail
spritesheet2_NomolosUseFlail:
  .byte $06
  .word spritesheet2_NomolosUseFlail0
  .word spritesheet2_NomolosUseFlail1
  .word $0000

.export spritesheet2_FlailBall
spritesheet2_FlailBall:
  .byte $01
  .word spritesheet2_FlailBall0
  .word spritesheet2_FlailBall1
  .word spritesheet2_FlailBall2
  .word spritesheet2_FlailBall3
  .word spritesheet2_FlailBall4
  .word spritesheet2_FlailBall5
  .word spritesheet2_FlailBall6
  .word spritesheet2_FlailBall7
  .word $0000

.export spritesheet2_NomolosFlailOverlay
spritesheet2_NomolosFlailOverlay:
  .byte $06
  .word spritesheet2_NomolosFlailOverlay0
  .word spritesheet2_NomolosFlailOverlay0
  .word $0000

.export spritesheet2_FlailItem
spritesheet2_FlailItem:
  .byte $0a
  .word spritesheet2_FlailItem0
  .word $0000

.export spritesheet2_BeedieBlob
spritesheet2_BeedieBlob:
  .byte $0a
  .word spritesheet2_Beedie0
  .word spritesheet2_Beedie1
  .word $0000

.export spritesheet2_GrankFly
spritesheet2_GrankFly:
  .byte $0a
  .word spritesheet2_Grank0
  .word spritesheet2_Grank1
  .word $0000

.export spritesheet2_NomolosUseSpear
spritesheet2_NomolosUseSpear:
  .byte $06
  .word spritesheet2_NomolosUseSpear0
  .word spritesheet2_NomolosUseSpear1
  .word $0000

.export spritesheet2_SpearFly
spritesheet2_SpearFly:
  .byte $0a
  .word spritesheet2_Spear0
  .word $0000

.export spritesheet2_SkelekinWalk
spritesheet2_SkelekinWalk:
  .byte $0a
  .word spritesheet2_Skelekin1
  .word spritesheet2_Skelekin0
  .word spritesheet2_Skelekin1
  .word spritesheet2_Skelekin2
  .word $0000

