
;Meta Sprite Table
.export spritesheet1_NomolosWalk0
spritesheet1_NomolosWalk0:
  .byte $08
  .byte $00,$00,$02,$00,$08
  .byte $00,$01,$02,$08,$00
  .byte $08,$18,$02,$00,$08
  .byte $08,$19,$02,$08,$00
  .byte $10,$2b,$02,$00,$08
  .byte $10,$2c,$02,$08,$00
  .byte $18,$3e,$02,$00,$08
  .byte $18,$3f,$02,$08,$00
.export spritesheet1_NomolosWalk1
spritesheet1_NomolosWalk1:
  .byte $08
  .byte $00,$02,$02,$00,$08
  .byte $00,$03,$02,$08,$00
  .byte $08,$1a,$00,$00,$08
  .byte $08,$1b,$02,$08,$00
  .byte $10,$2d,$02,$00,$08
  .byte $10,$2e,$02,$08,$00
  .byte $18,$40,$02,$00,$08
  .byte $18,$41,$02,$08,$00
.export spritesheet1_NomolosWalk2
spritesheet1_NomolosWalk2:
  .byte $08
  .byte $00,$05,$02,$00,$08
  .byte $00,$06,$02,$08,$00
  .byte $08,$1c,$02,$00,$08
  .byte $08,$1d,$02,$08,$00
  .byte $10,$2f,$02,$00,$08
  .byte $10,$30,$02,$08,$00
  .byte $18,$42,$02,$00,$08
  .byte $18,$43,$02,$08,$00
.export spritesheet1_NomolosJump0
spritesheet1_NomolosJump0:
  .byte $08
  .byte $00,$07,$02,$00,$08
  .byte $00,$08,$02,$08,$00
  .byte $08,$1e,$02,$00,$08
  .byte $08,$1f,$02,$08,$00
  .byte $10,$31,$02,$00,$08
  .byte $10,$32,$02,$08,$00
  .byte $18,$44,$02,$00,$08
  .byte $18,$45,$02,$08,$00
.export spritesheet1_NomolosWalkOverlay0
spritesheet1_NomolosWalkOverlay0:
  .byte $04
  .byte $01,$0d,$01,$00,$08
  .byte $01,$0e,$01,$08,$00
  .byte $09,$24,$01,$00,$08
  .byte $09,$25,$01,$08,$00
.export spritesheet1_NomolosWalkOverlay1
spritesheet1_NomolosWalkOverlay1:
  .byte $04
  .byte $01,$0f,$01,$00,$08
  .byte $01,$10,$01,$08,$00
  .byte $09,$26,$01,$00,$08
  .byte $09,$27,$01,$08,$00
.export spritesheet1_NomolosWalkOverlay2
spritesheet1_NomolosWalkOverlay2:
  .byte $04
  .byte $01,$0f,$01,$00,$08
  .byte $01,$11,$01,$08,$00
  .byte $09,$26,$01,$00,$08
  .byte $09,$27,$01,$08,$00
.export spritesheet1_NomolosJumpOverlay0
spritesheet1_NomolosJumpOverlay0:
  .byte $04
  .byte $01,$0d,$01,$00,$08
  .byte $01,$12,$01,$08,$00
  .byte $09,$24,$01,$00,$08
  .byte $09,$25,$01,$08,$00
.export spritesheet1_Heart0
spritesheet1_Heart0:
  .byte $01
  .byte $00,$39,$01,$00,$00
.export spritesheet1_Deentle0
spritesheet1_Deentle0:
  .byte $04
  .byte $00,$50,$03,$00,$08
  .byte $00,$51,$03,$08,$00
  .byte $08,$64,$03,$00,$08
  .byte $08,$65,$03,$08,$00
.export spritesheet1_Deentle1
spritesheet1_Deentle1:
  .byte $04
  .byte $00,$52,$03,$00,$08
  .byte $00,$53,$03,$08,$00
  .byte $08,$66,$03,$00,$08
  .byte $08,$67,$03,$08,$00
.export spritesheet1_Explosion0
spritesheet1_Explosion0:
  .byte $04
  .byte $00,$54,$02,$00,$08
  .byte $00,$55,$02,$08,$00
  .byte $08,$68,$02,$00,$08
  .byte $08,$69,$02,$08,$00
.export spritesheet1_Explosion1
spritesheet1_Explosion1:
  .byte $04
  .byte $00,$56,$02,$00,$08
  .byte $00,$57,$02,$08,$00
  .byte $08,$6a,$02,$00,$08
  .byte $08,$6b,$02,$08,$00
.export spritesheet1_Explosion2
spritesheet1_Explosion2:
  .byte $04
  .byte $00,$58,$02,$00,$08
  .byte $00,$59,$02,$08,$00
  .byte $08,$6c,$02,$00,$08
  .byte $08,$6d,$02,$08,$00
.export spritesheet1_Mouse0
spritesheet1_Mouse0:
  .byte $02
  .byte $00,$5a,$01,$00,$08
  .byte $00,$5b,$00,$08,$00
.export spritesheet1_SlumpedArmor0
spritesheet1_SlumpedArmor0:
  .byte $06
  .byte $08,$6f,$00,$00,$08
  .byte $08,$70,$00,$08,$00
  .byte $10,$89,$02,$00,$08
  .byte $10,$8a,$02,$08,$00
  .byte $18,$9f,$02,$00,$08
  .byte $18,$a0,$02,$08,$00
.export spritesheet1_SlumpedArmorOverlay0
spritesheet1_SlumpedArmorOverlay0:
  .byte $02
  .byte $08,$6e,$01,$00,$00
  .byte $10,$88,$01,$00,$00
.export spritesheet1_ScardyCat0
spritesheet1_ScardyCat0:
  .byte $08
  .byte $00,$5c,$02,$00,$08
  .byte $00,$5d,$02,$08,$00
  .byte $08,$71,$02,$00,$08
  .byte $08,$72,$02,$08,$00
  .byte $10,$8b,$02,$00,$08
  .byte $10,$8c,$02,$08,$00
  .byte $18,$a1,$02,$00,$08
  .byte $18,$a2,$02,$08,$00
.export spritesheet1_ScardyCatOverlay0
spritesheet1_ScardyCatOverlay0:
  .byte $04
  .byte $08,$73,$01,$00,$08
  .byte $08,$74,$01,$08,$00
  .byte $10,$8d,$01,$00,$08
  .byte $10,$8e,$01,$08,$00
.export spritesheet1_NomolosFight0
spritesheet1_NomolosFight0:
  .byte $0a
  .byte $f8,$4c,$02,$00,$08
  .byte $f8,$17,$00,$08,$00
  .byte $00,$5e,$02,$00,$08
  .byte $00,$5f,$02,$08,$00
  .byte $08,$75,$02,$00,$08
  .byte $08,$76,$02,$08,$00
  .byte $10,$8f,$02,$00,$08
  .byte $10,$90,$02,$08,$00
  .byte $18,$a3,$02,$00,$08
  .byte $18,$a4,$02,$08,$00
.export spritesheet1_NomolosFight1
spritesheet1_NomolosFight1:
  .byte $10
  .byte $00,$60,$02,$00,$08
  .byte $00,$61,$02,$08,$00
  .byte $00,$62,$00,$10,$f8
  .byte $00,$17,$00,$18,$f0
  .byte $08,$77,$02,$00,$08
  .byte $08,$78,$02,$08,$00
  .byte $08,$79,$02,$10,$f8
  .byte $08,$7a,$02,$18,$f0
  .byte $10,$91,$02,$00,$08
  .byte $10,$92,$02,$08,$00
  .byte $10,$93,$02,$10,$f8
  .byte $10,$94,$02,$18,$f0
  .byte $18,$a5,$02,$00,$08
  .byte $18,$a6,$02,$08,$00
  .byte $18,$a7,$02,$10,$f8
  .byte $18,$17,$00,$18,$f0
.export spritesheet1_NomolosFightOverlay0
spritesheet1_NomolosFightOverlay0:
  .byte $04
  .byte $01,$13,$01,$00,$08
  .byte $01,$14,$01,$08,$00
  .byte $09,$17,$00,$00,$08
  .byte $09,$28,$01,$08,$00
.export spritesheet1_NomolosFightOverlay1
spritesheet1_NomolosFightOverlay1:
  .byte $04
  .byte $01,$15,$01,$00,$08
  .byte $01,$16,$01,$08,$00
  .byte $09,$29,$01,$00,$08
  .byte $09,$2a,$01,$08,$00
.export spritesheet1_OneUp0
spritesheet1_OneUp0:
  .byte $04
  .byte $00,$3d,$00,$00,$08
  .byte $00,$3d,$00,$08,$00
  .byte $08,$4d,$02,$00,$08
  .byte $08,$4e,$02,$08,$00
.export spritesheet1_NomolosUseFlail0
spritesheet1_NomolosUseFlail0:
  .byte $0c
  .byte $00,$09,$02,$00,$08
  .byte $00,$0a,$02,$08,$00
  .byte $00,$0b,$02,$10,$f8
  .byte $08,$20,$02,$00,$08
  .byte $08,$21,$02,$08,$00
  .byte $08,$22,$02,$10,$f8
  .byte $10,$33,$02,$00,$08
  .byte $10,$34,$02,$08,$00
  .byte $10,$35,$02,$10,$f8
  .byte $18,$46,$02,$00,$08
  .byte $18,$47,$02,$08,$00
  .byte $18,$48,$02,$10,$f8
.export spritesheet1_NomolosUseFlail1
spritesheet1_NomolosUseFlail1:
  .byte $0c
  .byte $00,$0c,$02,$00,$08
  .byte $00,$0a,$02,$08,$00
  .byte $00,$0b,$02,$10,$f8
  .byte $08,$23,$02,$00,$08
  .byte $08,$21,$02,$08,$00
  .byte $08,$22,$02,$10,$f8
  .byte $10,$36,$02,$00,$08
  .byte $10,$37,$02,$08,$00
  .byte $10,$38,$02,$10,$f8
  .byte $18,$49,$02,$00,$08
  .byte $18,$4a,$02,$08,$00
  .byte $18,$4b,$02,$10,$f8
.export spritesheet1_FlailBall0
spritesheet1_FlailBall0:
  .byte $01
  .byte $f0,$3a,$02,$ea,$16
.export spritesheet1_FlailBall1
spritesheet1_FlailBall1:
  .byte $01
  .byte $ec,$3a,$02,$00,$00
.export spritesheet1_FlailBall2
spritesheet1_FlailBall2:
  .byte $01
  .byte $f0,$3a,$02,$16,$ea
.export spritesheet1_FlailBall3
spritesheet1_FlailBall3:
  .byte $01
  .byte $00,$3a,$02,$28,$d8
.export spritesheet1_FlailBall4
spritesheet1_FlailBall4:
  .byte $01
  .byte $10,$3a,$02,$16,$ea
.export spritesheet1_FlailBall5
spritesheet1_FlailBall5:
  .byte $01
  .byte $14,$3a,$02,$00,$00
.export spritesheet1_FlailBall6
spritesheet1_FlailBall6:
  .byte $01
  .byte $10,$3a,$02,$ea,$16
.export spritesheet1_FlailBall7
spritesheet1_FlailBall7:
  .byte $01
  .byte $00,$3a,$02,$d8,$28
.export spritesheet1_NomolosFlailOverlay0
spritesheet1_NomolosFlailOverlay0:
  .byte $04
  .byte $01,$13,$01,$03,$05
  .byte $01,$14,$01,$0b,$fd
  .byte $09,$17,$00,$03,$05
  .byte $09,$28,$01,$0b,$fd
.export spritesheet1_FlailItem0
spritesheet1_FlailItem0:
  .byte $02
  .byte $00,$3b,$02,$00,$08
  .byte $00,$3c,$02,$08,$00
.export spritesheet1_Beedie0
spritesheet1_Beedie0:
  .byte $04
  .byte $00,$80,$01,$00,$08
  .byte $00,$81,$01,$08,$00
  .byte $08,$97,$01,$00,$08
  .byte $08,$98,$01,$08,$00
.export spritesheet1_Beedie1
spritesheet1_Beedie1:
  .byte $04
  .byte $00,$82,$01,$00,$08
  .byte $00,$83,$01,$08,$00
  .byte $08,$99,$01,$00,$08
  .byte $08,$9a,$01,$08,$00
.export spritesheet1_Grank0
spritesheet1_Grank0:
  .byte $04
  .byte $00,$84,$03,$00,$08
  .byte $00,$85,$03,$08,$00
  .byte $08,$9b,$03,$00,$08
  .byte $08,$9c,$03,$08,$00
.export spritesheet1_Grank1
spritesheet1_Grank1:
  .byte $04
  .byte $00,$86,$03,$00,$08
  .byte $00,$87,$03,$08,$00
  .byte $08,$9d,$03,$00,$08
  .byte $08,$9e,$03,$08,$00
.export spritesheet1_NomolosUseSpear0
spritesheet1_NomolosUseSpear0:
  .byte $0a
  .byte $f8,$4f,$02,$00,$08
  .byte $f8,$17,$00,$08,$00
  .byte $00,$63,$02,$00,$08
  .byte $00,$5f,$02,$08,$00
  .byte $08,$7b,$02,$00,$08
  .byte $08,$76,$02,$08,$00
  .byte $10,$95,$02,$00,$08
  .byte $10,$90,$02,$08,$00
  .byte $18,$a3,$02,$00,$08
  .byte $18,$a4,$02,$08,$00
.export spritesheet1_NomolosUseSpear1
spritesheet1_NomolosUseSpear1:
  .byte $0c
  .byte $00,$60,$02,$00,$08
  .byte $00,$61,$02,$08,$00
  .byte $00,$62,$00,$10,$f8
  .byte $08,$77,$02,$00,$08
  .byte $08,$78,$02,$08,$00
  .byte $08,$7c,$02,$10,$f8
  .byte $10,$91,$02,$00,$08
  .byte $10,$92,$02,$08,$00
  .byte $10,$96,$02,$10,$f8
  .byte $18,$a5,$02,$00,$08
  .byte $18,$a6,$02,$08,$00
  .byte $18,$a7,$02,$10,$f8
.export spritesheet1_Spear0
spritesheet1_Spear0:
  .byte $03
  .byte $00,$7d,$00,$00,$10
  .byte $00,$7e,$02,$08,$08
  .byte $00,$7f,$02,$10,$00
.export spritesheet1_Bat0
spritesheet1_Bat0:
  .byte $02
  .byte $00,$b7,$01,$00,$08
  .byte $00,$b8,$01,$08,$00
.export spritesheet1_Bat1
spritesheet1_Bat1:
  .byte $02
  .byte $00,$c8,$01,$00,$08
  .byte $00,$c9,$01,$08,$00
.export spritesheet1_Batree0
spritesheet1_Batree0:
  .byte $0f
  .byte $00,$a8,$00,$00,$10
  .byte $00,$a9,$00,$08,$08
  .byte $00,$aa,$00,$10,$00
  .byte $08,$b3,$00,$00,$10
  .byte $08,$b4,$00,$08,$08
  .byte $08,$b5,$00,$10,$00
  .byte $10,$c4,$00,$00,$10
  .byte $10,$c5,$00,$08,$08
  .byte $10,$c6,$00,$10,$00
  .byte $18,$d5,$00,$00,$10
  .byte $18,$d6,$00,$08,$08
  .byte $18,$d7,$00,$10,$00
  .byte $20,$e3,$00,$00,$10
  .byte $20,$e4,$00,$08,$08
  .byte $20,$e5,$00,$10,$00
.export spritesheet1_Batree1
spritesheet1_Batree1:
  .byte $0f
  .byte $00,$a8,$00,$00,$10
  .byte $00,$a9,$00,$08,$08
  .byte $00,$aa,$00,$10,$00
  .byte $08,$b3,$00,$00,$10
  .byte $08,$b6,$00,$08,$08
  .byte $08,$b5,$00,$10,$00
  .byte $10,$c4,$00,$00,$10
  .byte $10,$c7,$00,$08,$08
  .byte $10,$c6,$00,$10,$00
  .byte $18,$d5,$00,$00,$10
  .byte $18,$d8,$00,$08,$08
  .byte $18,$d7,$00,$10,$00
  .byte $20,$e3,$00,$00,$10
  .byte $20,$e4,$00,$08,$08
  .byte $20,$e5,$00,$10,$00
.export spritesheet1_Owl0
spritesheet1_Owl0:
  .byte $0c
  .byte $00,$d9,$00,$00,$18
  .byte $00,$da,$00,$08,$10
  .byte $00,$db,$00,$10,$08
  .byte $00,$17,$00,$18,$00
  .byte $08,$e6,$00,$00,$18
  .byte $08,$e7,$00,$08,$10
  .byte $08,$e8,$00,$10,$08
  .byte $08,$e9,$00,$18,$00
  .byte $10,$f2,$00,$00,$18
  .byte $10,$f3,$00,$08,$10
  .byte $10,$f4,$00,$10,$08
  .byte $10,$f5,$00,$18,$00
.export spritesheet1_Owl1
spritesheet1_Owl1:
  .byte $0c
  .byte $00,$dc,$00,$00,$18
  .byte $00,$dd,$00,$08,$10
  .byte $00,$de,$00,$10,$08
  .byte $00,$df,$00,$18,$00
  .byte $08,$ea,$00,$00,$18
  .byte $08,$eb,$00,$08,$10
  .byte $08,$ec,$00,$10,$08
  .byte $08,$ed,$00,$18,$00
  .byte $10,$f6,$00,$00,$18
  .byte $10,$f7,$00,$08,$10
  .byte $10,$f8,$00,$10,$08
  .byte $10,$f9,$00,$18,$00
.export spritesheet1_Owl2
spritesheet1_Owl2:
  .byte $0c
  .byte $00,$17,$00,$00,$18
  .byte $00,$e0,$00,$08,$10
  .byte $00,$e1,$00,$10,$08
  .byte $00,$e2,$00,$18,$00
  .byte $08,$ee,$00,$00,$18
  .byte $08,$ef,$00,$08,$10
  .byte $08,$f0,$00,$10,$08
  .byte $08,$f1,$00,$18,$00
  .byte $10,$fa,$00,$00,$18
  .byte $10,$fb,$00,$08,$10
  .byte $10,$fc,$00,$10,$08
  .byte $10,$fd,$00,$18,$00

