
;Meta Sprite Table
.export spritesheet2_NomolosWalk0
spritesheet2_NomolosWalk0:
  .byte $08
  .byte $00,$00,$01,$00,$08
  .byte $00,$01,$01,$08,$00
  .byte $08,$18,$01,$00,$08
  .byte $08,$19,$01,$08,$00
  .byte $10,$2b,$01,$00,$08
  .byte $10,$2c,$01,$08,$00
  .byte $18,$3e,$01,$00,$08
  .byte $18,$3f,$01,$08,$00
.export spritesheet2_NomolosWalk1
spritesheet2_NomolosWalk1:
  .byte $08
  .byte $00,$02,$01,$00,$08
  .byte $00,$03,$01,$08,$00
  .byte $08,$1a,$00,$00,$08
  .byte $08,$1b,$01,$08,$00
  .byte $10,$2d,$01,$00,$08
  .byte $10,$2e,$01,$08,$00
  .byte $18,$40,$01,$00,$08
  .byte $18,$41,$01,$08,$00
.export spritesheet2_NomolosWalk2
spritesheet2_NomolosWalk2:
  .byte $08
  .byte $00,$05,$01,$00,$08
  .byte $00,$06,$01,$08,$00
  .byte $08,$1c,$01,$00,$08
  .byte $08,$1d,$01,$08,$00
  .byte $10,$2f,$01,$00,$08
  .byte $10,$30,$01,$08,$00
  .byte $18,$42,$01,$00,$08
  .byte $18,$43,$01,$08,$00
.export spritesheet2_NomolosJump0
spritesheet2_NomolosJump0:
  .byte $08
  .byte $00,$07,$01,$00,$08
  .byte $00,$08,$01,$08,$00
  .byte $08,$1e,$01,$00,$08
  .byte $08,$1f,$01,$08,$00
  .byte $10,$31,$01,$00,$08
  .byte $10,$32,$01,$08,$00
  .byte $18,$44,$01,$00,$08
  .byte $18,$45,$01,$08,$00
.export spritesheet2_NomolosWalkOverlay0
spritesheet2_NomolosWalkOverlay0:
  .byte $04
  .byte $01,$0d,$00,$00,$08
  .byte $01,$0e,$00,$08,$00
  .byte $09,$24,$00,$00,$08
  .byte $09,$25,$00,$08,$00
.export spritesheet2_NomolosWalkOverlay1
spritesheet2_NomolosWalkOverlay1:
  .byte $04
  .byte $01,$0f,$00,$00,$08
  .byte $01,$10,$00,$08,$00
  .byte $09,$26,$00,$00,$08
  .byte $09,$27,$00,$08,$00
.export spritesheet2_NomolosWalkOverlay2
spritesheet2_NomolosWalkOverlay2:
  .byte $04
  .byte $01,$0f,$00,$00,$08
  .byte $01,$11,$00,$08,$00
  .byte $09,$26,$00,$00,$08
  .byte $09,$27,$00,$08,$00
.export spritesheet2_NomolosJumpOverlay0
spritesheet2_NomolosJumpOverlay0:
  .byte $04
  .byte $01,$0d,$00,$00,$08
  .byte $01,$12,$00,$08,$00
  .byte $09,$24,$00,$00,$08
  .byte $09,$25,$00,$08,$00
.export spritesheet2_Heart0
spritesheet2_Heart0:
  .byte $01
  .byte $00,$39,$00,$00,$00
.export spritesheet2_Deentle0
spritesheet2_Deentle0:
  .byte $04
  .byte $00,$50,$02,$00,$08
  .byte $00,$51,$02,$08,$00
  .byte $08,$64,$02,$00,$08
  .byte $08,$65,$02,$08,$00
.export spritesheet2_Deentle1
spritesheet2_Deentle1:
  .byte $04
  .byte $00,$52,$02,$00,$08
  .byte $00,$53,$02,$08,$00
  .byte $08,$66,$02,$00,$08
  .byte $08,$67,$02,$08,$00
.export spritesheet2_Explosion0
spritesheet2_Explosion0:
  .byte $04
  .byte $00,$54,$01,$00,$08
  .byte $00,$55,$01,$08,$00
  .byte $08,$68,$01,$00,$08
  .byte $08,$69,$01,$08,$00
.export spritesheet2_Explosion1
spritesheet2_Explosion1:
  .byte $04
  .byte $00,$56,$01,$00,$08
  .byte $00,$57,$01,$08,$00
  .byte $08,$6a,$01,$00,$08
  .byte $08,$6b,$01,$08,$00
.export spritesheet2_Explosion2
spritesheet2_Explosion2:
  .byte $04
  .byte $00,$58,$01,$00,$08
  .byte $00,$59,$01,$08,$00
  .byte $08,$6c,$01,$00,$08
  .byte $08,$6d,$01,$08,$00
.export spritesheet2_Mouse0
spritesheet2_Mouse0:
  .byte $02
  .byte $00,$5a,$00,$00,$08
  .byte $00,$5b,$00,$08,$00
.export spritesheet2_SlumpedArmor0
spritesheet2_SlumpedArmor0:
  .byte $06
  .byte $08,$6f,$00,$00,$08
  .byte $08,$70,$00,$08,$00
  .byte $10,$89,$01,$00,$08
  .byte $10,$8a,$01,$08,$00
  .byte $18,$9f,$01,$00,$08
  .byte $18,$a0,$01,$08,$00
.export spritesheet2_SlumpedArmorOverlay0
spritesheet2_SlumpedArmorOverlay0:
  .byte $02
  .byte $08,$6e,$00,$00,$00
  .byte $10,$88,$00,$00,$00
.export spritesheet2_ScardyCat0
spritesheet2_ScardyCat0:
  .byte $08
  .byte $00,$5c,$01,$00,$08
  .byte $00,$5d,$01,$08,$00
  .byte $08,$71,$01,$00,$08
  .byte $08,$72,$01,$08,$00
  .byte $10,$8b,$01,$00,$08
  .byte $10,$8c,$01,$08,$00
  .byte $18,$a1,$01,$00,$08
  .byte $18,$a2,$01,$08,$00
.export spritesheet2_ScardyCatOverlay0
spritesheet2_ScardyCatOverlay0:
  .byte $04
  .byte $08,$73,$00,$00,$08
  .byte $08,$74,$00,$08,$00
  .byte $10,$8d,$00,$00,$08
  .byte $10,$8e,$00,$08,$00
.export spritesheet2_NomolosFight0
spritesheet2_NomolosFight0:
  .byte $0a
  .byte $f8,$4c,$01,$00,$08
  .byte $f8,$17,$00,$08,$00
  .byte $00,$5e,$01,$00,$08
  .byte $00,$5f,$01,$08,$00
  .byte $08,$75,$01,$00,$08
  .byte $08,$76,$01,$08,$00
  .byte $10,$8f,$01,$00,$08
  .byte $10,$90,$01,$08,$00
  .byte $18,$a3,$01,$00,$08
  .byte $18,$a4,$01,$08,$00
.export spritesheet2_NomolosFight1
spritesheet2_NomolosFight1:
  .byte $10
  .byte $00,$60,$01,$00,$08
  .byte $00,$61,$01,$08,$00
  .byte $00,$62,$00,$10,$f8
  .byte $00,$17,$00,$18,$f0
  .byte $08,$77,$01,$00,$08
  .byte $08,$78,$01,$08,$00
  .byte $08,$79,$01,$10,$f8
  .byte $08,$7a,$01,$18,$f0
  .byte $10,$91,$01,$00,$08
  .byte $10,$92,$01,$08,$00
  .byte $10,$93,$01,$10,$f8
  .byte $10,$94,$01,$18,$f0
  .byte $18,$a5,$01,$00,$08
  .byte $18,$a6,$01,$08,$00
  .byte $18,$a7,$01,$10,$f8
  .byte $18,$17,$00,$18,$f0
.export spritesheet2_NomolosFightOverlay0
spritesheet2_NomolosFightOverlay0:
  .byte $04
  .byte $01,$13,$00,$00,$08
  .byte $01,$14,$00,$08,$00
  .byte $09,$17,$00,$00,$08
  .byte $09,$28,$00,$08,$00
.export spritesheet2_NomolosFightOverlay1
spritesheet2_NomolosFightOverlay1:
  .byte $04
  .byte $01,$15,$00,$00,$08
  .byte $01,$16,$00,$08,$00
  .byte $09,$29,$00,$00,$08
  .byte $09,$2a,$00,$08,$00
.export spritesheet2_OneUp0
spritesheet2_OneUp0:
  .byte $04
  .byte $00,$3d,$00,$00,$08
  .byte $00,$3d,$00,$08,$00
  .byte $08,$4d,$01,$00,$08
  .byte $08,$4e,$01,$08,$00
.export spritesheet2_NomolosUseFlail0
spritesheet2_NomolosUseFlail0:
  .byte $0c
  .byte $00,$09,$01,$00,$08
  .byte $00,$0a,$01,$08,$00
  .byte $00,$0b,$01,$10,$f8
  .byte $08,$20,$01,$00,$08
  .byte $08,$21,$01,$08,$00
  .byte $08,$22,$01,$10,$f8
  .byte $10,$33,$01,$00,$08
  .byte $10,$34,$01,$08,$00
  .byte $10,$35,$01,$10,$f8
  .byte $18,$46,$01,$00,$08
  .byte $18,$47,$01,$08,$00
  .byte $18,$48,$01,$10,$f8
.export spritesheet2_NomolosUseFlail1
spritesheet2_NomolosUseFlail1:
  .byte $0c
  .byte $00,$0c,$01,$00,$08
  .byte $00,$0a,$01,$08,$00
  .byte $00,$0b,$01,$10,$f8
  .byte $08,$23,$01,$00,$08
  .byte $08,$21,$01,$08,$00
  .byte $08,$22,$01,$10,$f8
  .byte $10,$36,$01,$00,$08
  .byte $10,$37,$01,$08,$00
  .byte $10,$38,$01,$10,$f8
  .byte $18,$49,$01,$00,$08
  .byte $18,$4a,$01,$08,$00
  .byte $18,$4b,$01,$10,$f8
.export spritesheet2_FlailBall0
spritesheet2_FlailBall0:
  .byte $01
  .byte $f0,$3a,$01,$ea,$16
.export spritesheet2_FlailBall1
spritesheet2_FlailBall1:
  .byte $01
  .byte $ec,$3a,$01,$00,$00
.export spritesheet2_FlailBall2
spritesheet2_FlailBall2:
  .byte $01
  .byte $f0,$3a,$01,$16,$ea
.export spritesheet2_FlailBall3
spritesheet2_FlailBall3:
  .byte $01
  .byte $00,$3a,$01,$28,$d8
.export spritesheet2_FlailBall4
spritesheet2_FlailBall4:
  .byte $01
  .byte $10,$3a,$01,$16,$ea
.export spritesheet2_FlailBall5
spritesheet2_FlailBall5:
  .byte $01
  .byte $14,$3a,$01,$00,$00
.export spritesheet2_FlailBall6
spritesheet2_FlailBall6:
  .byte $01
  .byte $10,$3a,$01,$ea,$16
.export spritesheet2_FlailBall7
spritesheet2_FlailBall7:
  .byte $01
  .byte $00,$3a,$01,$d8,$28
.export spritesheet2_NomolosFlailOverlay0
spritesheet2_NomolosFlailOverlay0:
  .byte $04
  .byte $01,$13,$00,$03,$05
  .byte $01,$14,$00,$0b,$fd
  .byte $09,$17,$00,$03,$05
  .byte $09,$28,$00,$0b,$fd
.export spritesheet2_FlailItem0
spritesheet2_FlailItem0:
  .byte $02
  .byte $00,$3b,$01,$00,$08
  .byte $00,$3c,$01,$08,$00
.export spritesheet2_Beedie0
spritesheet2_Beedie0:
  .byte $04
  .byte $00,$80,$00,$00,$08
  .byte $00,$81,$00,$08,$00
  .byte $08,$97,$00,$00,$08
  .byte $08,$98,$00,$08,$00
.export spritesheet2_Beedie1
spritesheet2_Beedie1:
  .byte $04
  .byte $00,$82,$00,$00,$08
  .byte $00,$83,$00,$08,$00
  .byte $08,$99,$00,$00,$08
  .byte $08,$9a,$00,$08,$00
.export spritesheet2_Grank0
spritesheet2_Grank0:
  .byte $04
  .byte $00,$84,$02,$00,$08
  .byte $00,$85,$02,$08,$00
  .byte $08,$9b,$02,$00,$08
  .byte $08,$9c,$02,$08,$00
.export spritesheet2_Grank1
spritesheet2_Grank1:
  .byte $04
  .byte $00,$86,$02,$00,$08
  .byte $00,$87,$02,$08,$00
  .byte $08,$9d,$02,$00,$08
  .byte $08,$9e,$02,$08,$00
.export spritesheet2_NomolosUseSpear0
spritesheet2_NomolosUseSpear0:
  .byte $0a
  .byte $f8,$4f,$01,$00,$08
  .byte $f8,$17,$00,$08,$00
  .byte $00,$63,$01,$00,$08
  .byte $00,$5f,$01,$08,$00
  .byte $08,$7b,$01,$00,$08
  .byte $08,$76,$01,$08,$00
  .byte $10,$95,$01,$00,$08
  .byte $10,$90,$01,$08,$00
  .byte $18,$a3,$01,$00,$08
  .byte $18,$a4,$01,$08,$00
.export spritesheet2_NomolosUseSpear1
spritesheet2_NomolosUseSpear1:
  .byte $0c
  .byte $00,$60,$01,$00,$08
  .byte $00,$61,$01,$08,$00
  .byte $00,$62,$00,$10,$f8
  .byte $08,$77,$01,$00,$08
  .byte $08,$78,$01,$08,$00
  .byte $08,$7c,$01,$10,$f8
  .byte $10,$91,$01,$00,$08
  .byte $10,$92,$01,$08,$00
  .byte $10,$96,$01,$10,$f8
  .byte $18,$a5,$01,$00,$08
  .byte $18,$a6,$01,$08,$00
  .byte $18,$a7,$01,$10,$f8
.export spritesheet2_Spear0
spritesheet2_Spear0:
  .byte $03
  .byte $00,$7d,$00,$00,$10
  .byte $00,$7e,$01,$08,$08
  .byte $00,$7f,$01,$10,$00
.export spritesheet2_Skelekin0
spritesheet2_Skelekin0:
  .byte $08
  .byte $00,$a8,$01,$00,$08
  .byte $00,$17,$00,$08,$00
  .byte $08,$a9,$01,$00,$08
  .byte $08,$aa,$01,$08,$00
  .byte $10,$b0,$01,$00,$08
  .byte $10,$b1,$01,$08,$00
  .byte $18,$b6,$01,$00,$08
  .byte $18,$b7,$01,$08,$00
.export spritesheet2_Skelekin1
spritesheet2_Skelekin1:
  .byte $08
  .byte $00,$a8,$01,$00,$08
  .byte $00,$17,$00,$08,$00
  .byte $08,$a9,$01,$00,$08
  .byte $08,$ab,$01,$08,$00
  .byte $10,$b2,$01,$00,$08
  .byte $10,$17,$00,$08,$00
  .byte $18,$b6,$01,$00,$08
  .byte $18,$17,$00,$08,$00
.export spritesheet2_Skelekin2
spritesheet2_Skelekin2:
  .byte $08
  .byte $00,$a8,$01,$00,$08
  .byte $00,$17,$00,$08,$00
  .byte $08,$ac,$01,$00,$08
  .byte $08,$ad,$01,$08,$00
  .byte $10,$b3,$01,$00,$08
  .byte $10,$b1,$01,$08,$00
  .byte $18,$b6,$01,$00,$08
  .byte $18,$b7,$01,$08,$00

