.ifndef SPRITESHEET1_INC
SPRITESHEET1_INC = 1

sprite_sheet_1_bank = $02

.include "spritesheet1_sprites_imports.inc"
.include "spritesheet1_animations_imports.inc"

.import flail_item_update
.import oneup_update
.import mouse_update
.import explosion_update
.import deentle_update
.import exit_level_update
.import beedie_update
.import grank_update
.import spear_item_update
.import skelekin_update

.endif
