.ifndef SPRITESHEET1_INC
SPRITESHEET1_INC = 1

.import NomolosWalk0
.import NomolosWalk1
.import NomolosWalk2
.import NomolosJump0
.import NomolosWalkOverlay0
.import NomolosWalkOverlay1
.import NomolosWalkOverlay2
.import NomolosJumpOverlay0
.import Heart0
.import Deentle0
.import Deentle1
.import Explosion0
.import Explosion1
.import Explosion2
.import Mouse0
.import SlumpedArmor0
.import SlumpedArmorOverlay0
.import ScardyCat0
.import ScardyCatOverlay0
.import NomolosFight0
.import NomolosFight1
.import NomolosFightOverlay0
.import NomolosFightOverlay1
.import OneUp0
.import NomolosUseFlail0
.import NomolosUseFlail1
.import FlailBall0
.import FlailBall1
.import FlailBall2
.import FlailBall3
.import FlailBall4
.import FlailBall5
.import FlailBall6
.import FlailBall7
.import NomolosFlailOverlay0
.import FlailItem0

.import NomolosWalk
.import NomolosJump
.import NomolosWalkOverlay
.import NomolosJumpOverlay
.import Heart
.import DeentleWalk
.import Explosion
.import Mouse
.import NomolosFight
.import NomolosFightOverlay
.import NomolosUseFlail
.import FlailBall
.import NomolosFlailOverlay
.import FlailItem

.import flailItemUpdate
.import oneUpUpdate
.import mouseUpdate
.import explosionUpdate
.import deentleUpdate
.import exitLevelUpdate

.endif
