.ifndef CHR_SIZES_INC
CHR_SIZES_INC = 1

Nomolos_chr_size = 131
Deentle_chr_size = 8
Explosion_chr_size = 12
Beedie_chr_size = 8
Grank_chr_size = 8
Bat_chr_size = 4
Batree_chr_size = 18
Owl_chr_size = 34
Snuffer_chr_size = 30
Skelekin_chr_size = 12
Snail_chr_size = 12
Dragon_chr_size = 33
IceBall_chr_size = 12
Shark_chr_size = 18
Stalactite_chr_size = 4
DragonFace_chr_size = 12
FireGuy_chr_size = 12
Phoenix_chr_size = 24
Fireball_chr_size = 12
Snake_chr_size = 12
Thoguth_chr_size = 45
bigfireball_chr_size = 12
statue_chr_size = 13
raven_chr_size = 43
sheep_chr_size = 35
bee_chr_size = 21

.endif
