.ifndef SPRITESHEET1_INC
SPRITESHEET1_INC = 1

.include "chr_sizes.inc"

spritesheet_1_bank = 13
spritesheet_1_patterns_bank = 14

.include "spritesheet1_sprites_imports.inc"
.include "spritesheet1_animations_imports.inc"
.include "spritesheet1_patterns_imports.inc"
.include "spritesheet_common_animations_imports.inc"
.include "spritesheet_common_sprites_imports.inc"
.include "spritesheet_common_patterns_imports.inc"

.endif
