;Animations
.export spritesheet1_NomolosWalk
spritesheet1_NomolosWalk:
  .byte $06
  .word spritesheet1_NomolosWalk0
  .word spritesheet1_NomolosWalk1
  .word spritesheet1_NomolosWalk0
  .word spritesheet1_NomolosWalk2
  .word $0000

.export spritesheet1_NomolosJump
spritesheet1_NomolosJump:
  .byte $0a
  .word spritesheet1_NomolosJump0
  .word $0000

.export spritesheet1_NomolosWalkOverlay
spritesheet1_NomolosWalkOverlay:
  .byte $0a
  .word spritesheet1_NomolosWalkOverlay0
  .word spritesheet1_NomolosWalkOverlay1
  .word spritesheet1_NomolosWalkOverlay0
  .word spritesheet1_NomolosWalkOverlay2
  .word $0000

.export spritesheet1_NomolosJumpOverlay
spritesheet1_NomolosJumpOverlay:
  .byte $0a
  .word spritesheet1_NomolosJumpOverlay0
  .word $0000

.export spritesheet1_Heart
spritesheet1_Heart:
  .byte $0a
  .word spritesheet1_Heart0
  .word $0000

.export spritesheet1_DeentleWalk
spritesheet1_DeentleWalk:
  .byte $0a
  .word spritesheet1_Deentle0
  .word spritesheet1_Deentle1
  .word $0000

.export spritesheet1_Explosion
spritesheet1_Explosion:
  .byte 3
  .word spritesheet1_Explosion2
  .word spritesheet1_Explosion1
  .word spritesheet1_Explosion0
  .word $0000

.export spritesheet1_Mouse
spritesheet1_Mouse:
  .byte $0a
  .word spritesheet1_Mouse0
  .word $0000

.export spritesheet1_NomolosFight
spritesheet1_NomolosFight:
  .byte $06
  .word spritesheet1_NomolosFight0
  .word spritesheet1_NomolosFight1
  .word $0000

.export spritesheet1_NomolosFightOverlay
spritesheet1_NomolosFightOverlay:
  .byte $06
  .word spritesheet1_NomolosFightOverlay0
  .word spritesheet1_NomolosFightOverlay1
  .word $0000

.export spritesheet1_NomolosUseFlail
spritesheet1_NomolosUseFlail:
  .byte $06
  .word spritesheet1_NomolosUseFlail0
  .word spritesheet1_NomolosUseFlail1
  .word $0000

.export spritesheet1_FlailBall
spritesheet1_FlailBall:
  .byte $01
  .word spritesheet1_FlailBall0
  .word spritesheet1_FlailBall1
  .word spritesheet1_FlailBall2
  .word spritesheet1_FlailBall3
  .word spritesheet1_FlailBall4
  .word spritesheet1_FlailBall5
  .word spritesheet1_FlailBall6
  .word spritesheet1_FlailBall7
  .word $0000

.export spritesheet1_NomolosFlailOverlay
spritesheet1_NomolosFlailOverlay:
  .byte $06
  .word spritesheet1_NomolosFlailOverlay0
  .word spritesheet1_NomolosFlailOverlay0
  .word $0000

.export spritesheet1_FlailItem
spritesheet1_FlailItem:
  .byte $0a
  .word spritesheet1_FlailItem0
  .word $0000

.export spritesheet1_BeedieBlob
spritesheet1_BeedieBlob:
  .byte $0a
  .word spritesheet1_Beedie0
  .word spritesheet1_Beedie1
  .word $0000

.export spritesheet1_GrankFly
spritesheet1_GrankFly:
  .byte $0a
  .word spritesheet1_Grank0
  .word spritesheet1_Grank1
  .word $0000

.export spritesheet1_NomolosUseSpear
spritesheet1_NomolosUseSpear:
  .byte $06
  .word spritesheet1_NomolosUseSpear0
  .word spritesheet1_NomolosUseSpear1
  .word $0000

.export spritesheet1_SpearFly
spritesheet1_SpearFly:
  .byte $0a
  .word spritesheet1_Spear0
  .word $0000

.export spritesheet1_BatFly
spritesheet1_BatFly:
  .byte $0a
  .word spritesheet1_Bat0
  .word spritesheet1_Bat1
  .word $0000

.export spritesheet1_Batree
spritesheet1_Batree:
  .byte $0a
  .word spritesheet1_Batree0
  .word spritesheet1_Batree1
  .word $0000

.export spritesheet1_OwlFly
spritesheet1_OwlFly:
  .byte $0a
  .word spritesheet1_Owl0
  .word spritesheet1_Owl1
  .word $0000

.export spritesheet1_OwlAttack
spritesheet1_OwlAttack:
  .byte $0a
  .word spritesheet1_Owl2
  .word $0000

.export spritesheet1_SnufferRun
spritesheet1_SnufferRun:
  .byte $0a
  .word spritesheet1_Snuffer0
  .word spritesheet1_Snuffer1
  .word $0000

.export spritesheet1_SnufferBite
spritesheet1_SnufferBite:
  .byte $0a
  .word spritesheet1_Snuffer2
  .word $0000

.export spritesheet1_SkelekinWalk
spritesheet1_SkelekinWalk:
  .byte $0a
  .word spritesheet1_Skelekin1
  .word spritesheet1_Skelekin0
  .word spritesheet1_Skelekin1
  .word spritesheet1_Skelekin2
  .word $0000

.export spritesheet1_SnailCrawl
spritesheet1_SnailCrawl:
  .byte $28
  .word spritesheet1_Snail0
  .word spritesheet1_Snail1
  .word $0000

.export spritesheet1_DragonFly
spritesheet1_DragonFly:
  .byte $05
  .word spritesheet1_Dragon0
  .word spritesheet1_Dragon1
  .word spritesheet1_Dragon2
  .word spritesheet1_Dragon1
  .word $0000
  
.export spritesheet1_IceBallFly
spritesheet1_IceBallFly:
  .byte $02
  .word spritesheet1_IceBall2
  .word spritesheet1_IceBall1
  .word spritesheet1_IceBall0
  .word spritesheet1_IceBall1
  .word $0000

.export spritesheet1_SharkLeap
spritesheet1_SharkLeap:
  .byte 25
  .word spritesheet1_Shark0
  .word spritesheet1_Shark1
  .word spritesheet1_Shark2
  .word $0000
