.ifndef SPRITESHEET1_SPRITES_IMPORTS_INC
SPRITESHEET1_SPRITES_IMPORTS_INC = 1

.global spritesheet1_Deentle0
.global spritesheet1_Deentle1
.global spritesheet1_Beedie0
.global spritesheet1_Beedie1
.global spritesheet1_Grank0
.global spritesheet1_Grank1
.global spritesheet1_Batree0
.global spritesheet1_Batree1
.global spritesheet1_Owl0
.global spritesheet1_Owl1
.global spritesheet1_Owl2
.global spritesheet1_Snuffer0
.global spritesheet1_Snuffer1
.global spritesheet1_Snuffer2
.global spritesheet1_Snail0
.global spritesheet1_Snail1
.global spritesheet1_Dragon0
.global spritesheet1_Dragon1
.global spritesheet1_Dragon2
.global spritesheet1_IceBall0
.global spritesheet1_IceBall1
.global spritesheet1_IceBall2
.global spritesheet1_Shark0
.global spritesheet1_Shark1
.global spritesheet1_Shark2
.global spritesheet1_Stalactite0
.global spritesheet1_DragonFace0
.global spritesheet1_DragonFace1
.global spritesheet1_GrubselimBojEyes0
.global spritesheet1_GrubselimBojEyes1
.global spritesheet1_GrubselimBojMouth0
.global spritesheet1_GrubselimBojMouth1
.global spritesheet1_bigfireball0
.global spritesheet1_bigfireball1
.global spritesheet1_bigfireball2

.endif
