.ifndef SPRITESHEET2_ANIMATIONS_IMPORTS_INC
SPRITESHEET2_ANIMATIONS_IMPORTS_INC = 1

.global spritesheet2_PhoenixFly
.global spritesheet2_FireballFly
.global spritesheet2_SnakeSlither
.global spritesheet2_ThoguthMarch
.global spritesheet2_ThoguthHammerfall
.global spritesheet2_ThoguthLightning
.global spritesheet2_raven_fly
.global spritesheet2_SheepButt
.global spritesheet2_BeeFly

.endif
