.ifndef SPRITESHEET1_PATTERNS_IMPORTS_INC
SPRITESHEET1_PATTERNS_IMPORTS_INC = 1

.global spritesheet1_Deentle_chr
.global spritesheet1_Beedie_chr
.global spritesheet1_Grank_chr
.global spritesheet1_Snuffer_chr
.global spritesheet1_Owl_chr
.global spritesheet1_Batree_chr
.ifndef DEMO_BUILD
.global spritesheet1_Skelekin_chr
.global spritesheet1_Thoguth_chr
.global spritesheet1_LightningBolt_chr
.global spritesheet1_Snail_chr
.global spritesheet1_Dragon_chr
.global spritesheet1_IceBall_chr
.global spritesheet1_Shark_chr
.global spritesheet1_Stalactite_chr
.global spritesheet1_DragonFace_chr
.global spritesheet1_GrubselimBoj_chr
.global spritesheet1_bigfireball_chr
.global spritesheet1_Boulder_chr
.else
spritesheet1_Skelekin_chr = 0
spritesheet1_Thoguth_chr = 0
spritesheet1_LightningBolt_chr = 0
spritesheet1_Snail_chr = 0
spritesheet1_Dragon_chr = 0
spritesheet1_IceBall_chr = 0
spritesheet1_Shark_chr = 0
spritesheet1_Stalactite_chr = 0
spritesheet1_DragonFace_chr = 0
spritesheet1_GrubselimBoj_chr = 0
spritesheet1_bigfireball_chr = 0
spritesheet1_Boulder_chr = 0
.endif

.endif