.ifndef SPRITESHEET1_ANIMATIONS_IMPORTS_INC
SPRITESHEET1_ANIMATIONS_IMPORTS_INC = 1

.global spritesheet1_NomolosWalk
.global spritesheet1_nomolos_jump
.global spritesheet1_nomolos_walk_overlay
.global spritesheet1_nomolos_jump_overlay
.global spritesheet1_Heart
.global spritesheet1_DeentleWalk
.global spritesheet1_Explosion
.global spritesheet1_Mouse
.global spritesheet1_nomolos_fight
.global spritesheet1_nomolos_fight_overlay
.global spritesheet1_NomolosUseFlail
.global spritesheet1_FlailBall
.global spritesheet1_nomolos_flail_overlay
.global spritesheet1_FlailItem
.global spritesheet1_BeedieBlob
.global spritesheet1_GrankFly
.global spritesheet1_NomolosUseSpear
.global spritesheet1_SpearFly
.global spritesheet1_BatFly
.global spritesheet1_Batree
.global spritesheet1_OwlFly
.global spritesheet1_OwlAttack
.global spritesheet1_SnufferRun
.global spritesheet1_SnufferBite
.global spritesheet1_SkelekinWalk
.global spritesheet1_SnailCrawl
.global spritesheet1_DragonFly
.global spritesheet1_IceBallFly
.global spritesheet1_SharkLeap
.global spritesheet1_PhoenixFly
.global spritesheet1_FireballFly
.global spritesheet1_SnakeSlither
.global spritesheet1_ThoguthMarch
.global spritesheet1_ThoguthHammerfall
.global spritesheet1_ThoguthLightning
.global spritesheet1_bigfireballfly
.global spritesheet1_raven_fly

.endif
