.ifndef SPRITESHEET_COMMON_ANIMATIONS_IMPORTS_INC
SPRITESHEET_COMMON_ANIMATIONS_IMPORTS_INC = 1

.global spritesheet_common_NomolosWalk
.global spritesheet_common_nomolos_jump
.global spritesheet_common_nomolos_walk_overlay
.global spritesheet_common_nomolos_jump_overlay
.global spritesheet_common_Heart
.global spritesheet_common_Mouse
.global spritesheet_common_nomolos_fight
.global spritesheet_common_nomolos_fight_overlay
.global spritesheet_common_NomolosUseFlail
.global spritesheet_common_FlailBall
.global spritesheet_common_nomolos_flail_overlay
.global spritesheet_common_FlailItem
.global spritesheet_common_NomolosUseSpear
.global spritesheet_common_SpearFly
.global spritesheet_common_Explosion

.endif
