.include "spritesheet_common_sprites_imports.inc"

;Meta Sprite Table
.ifndef spritesheet_common_NomolosWalk0
spritesheet_common_NomolosWalk0:
.endif
  .byte $08
  .byte $00,$00,$00,$00,$08
  .byte $00,$01,$00,$08,$00
  .byte $08,$02,$00,$00,$08
  .byte $08,$03,$00,$08,$00
  .byte $10,$04,$00,$00,$08
  .byte $10,$05,$00,$08,$00
  .byte $18,$06,$00,$00,$08
  .byte $18,$07,$00,$08,$00
.ifndef spritesheet_common_NomolosWalk1
spritesheet_common_NomolosWalk1:
.endif
  .byte $08
  .byte $00,$08,$00,$00,$08
  .byte $00,$09,$00,$08,$00
  .byte $08,$0a,$00,$00,$08
  .byte $08,$0b,$00,$08,$00
  .byte $10,$0c,$00,$00,$08
  .byte $10,$0d,$00,$08,$00
  .byte $18,$0e,$00,$00,$08
  .byte $18,$0f,$00,$08,$00
.ifndef spritesheet_common_NomolosWalk2
spritesheet_common_NomolosWalk2:
.endif
  .byte $08
  .byte $00,$10,$00,$00,$08
  .byte $00,$11,$00,$08,$00
  .byte $08,$12,$00,$00,$08
  .byte $08,$13,$00,$08,$00
  .byte $10,$14,$00,$00,$08
  .byte $10,$15,$00,$08,$00
  .byte $18,$16,$00,$00,$08
  .byte $18,$17,$00,$08,$00
.ifndef spritesheet_common_nomolos_jump0
spritesheet_common_nomolos_jump0:
.endif
  .byte $08
  .byte $00,$18,$00,$00,$08
  .byte $00,$19,$00,$08,$00
  .byte $08,$1a,$00,$00,$08
  .byte $08,$1b,$00,$08,$00
  .byte $10,$1c,$00,$00,$08
  .byte $10,$1d,$00,$08,$00
  .byte $18,$1e,$00,$00,$08
  .byte $18,$1f,$00,$08,$00
.ifndef spritesheet_common_nomolos_walk_overlay0
spritesheet_common_nomolos_walk_overlay0:
.endif
  .byte $04
  .byte $01,$20,$01,$00,$08
  .byte $01,$21,$01,$08,$00
  .byte $09,$22,$01,$00,$08
  .byte $09,$23,$01,$08,$00
.ifndef spritesheet_common_nomolos_walk_overlay1
spritesheet_common_nomolos_walk_overlay1:
.endif
  .byte $04
  .byte $01,$24,$01,$00,$08
  .byte $01,$25,$01,$08,$00
  .byte $09,$26,$01,$00,$08
  .byte $09,$27,$01,$08,$00
.ifndef spritesheet_common_nomolos_walk_overlay2
spritesheet_common_nomolos_walk_overlay2:
.endif
  .byte $04
  .byte $01,$24,$01,$00,$08
  .byte $01,$28,$01,$08,$00
  .byte $09,$26,$01,$00,$08
  .byte $09,$27,$01,$08,$00
.ifndef spritesheet_common_nomolos_jump_overlay0
spritesheet_common_nomolos_jump_overlay0:
.endif
  .byte $04
  .byte $01,$20,$01,$00,$08
  .byte $01,$29,$01,$08,$00
  .byte $09,$22,$01,$00,$08
  .byte $09,$23,$01,$08,$00
.ifndef spritesheet_common_Heart0
spritesheet_common_Heart0:
.endif
  .byte $01
  .byte $00,$2a,$01,$00,$00
.ifndef spritesheet_common_Mouse0
spritesheet_common_Mouse0:
.endif
  .byte $02
  .byte $00,$2b,$01,$00,$08
  .byte $00,$2c,$00,$08,$00
.ifndef spritesheet_common_SlumpedArmor0
spritesheet_common_SlumpedArmor0:
.endif
  .byte $06
  .byte $08,$2d,$00,$00,$08
  .byte $08,$2e,$00,$08,$00
  .byte $10,$2f,$00,$00,$08
  .byte $10,$30,$00,$08,$00
  .byte $18,$31,$00,$00,$08
  .byte $18,$32,$00,$08,$00
.ifndef spritesheet_common_SlumpedArmorOverlay0
spritesheet_common_SlumpedArmorOverlay0:
.endif
  .byte $02
  .byte $08,$33,$01,$00,$00
  .byte $10,$34,$01,$00,$00
.ifndef spritesheet_common_ScardyCat0
spritesheet_common_ScardyCat0:
.endif
  .byte $08
  .byte $00,$35,$00,$00,$08
  .byte $00,$36,$00,$08,$00
  .byte $08,$37,$00,$00,$08
  .byte $08,$38,$00,$08,$00
  .byte $10,$39,$00,$00,$08
  .byte $10,$3a,$00,$08,$00
  .byte $18,$3b,$00,$00,$08
  .byte $18,$3c,$00,$08,$00
.ifndef spritesheet_common_ScardyCatOverlay0
spritesheet_common_ScardyCatOverlay0:
.endif
  .byte $04
  .byte $08,$3d,$01,$00,$08
  .byte $08,$3e,$01,$08,$00
  .byte $10,$3f,$01,$00,$08
  .byte $10,$40,$01,$08,$00
.ifndef spritesheet_common_nomolos_fight0
spritesheet_common_nomolos_fight0:
.endif
  .byte $0a
  .byte $f8,$41,$00,$00,$08
  .byte $f8,$42,$00,$08,$00
  .byte $00,$43,$00,$00,$08
  .byte $00,$44,$00,$08,$00
  .byte $08,$45,$00,$00,$08
  .byte $08,$46,$00,$08,$00
  .byte $10,$47,$00,$00,$08
  .byte $10,$48,$00,$08,$00
  .byte $18,$49,$00,$00,$08
  .byte $18,$4a,$00,$08,$00
.ifndef spritesheet_common_nomolos_fight1
spritesheet_common_nomolos_fight1:
.endif
  .byte $10
  .byte $00,$4b,$00,$00,$08
  .byte $00,$4c,$00,$08,$00
  .byte $00,$4d,$00,$10,$f8
  .byte $00,$42,$00,$18,$f0
  .byte $08,$4e,$00,$00,$08
  .byte $08,$4f,$00,$08,$00
  .byte $08,$50,$00,$10,$f8
  .byte $08,$51,$00,$18,$f0
  .byte $10,$52,$00,$00,$08
  .byte $10,$53,$00,$08,$00
  .byte $10,$54,$00,$10,$f8
  .byte $10,$55,$00,$18,$f0
  .byte $18,$56,$00,$00,$08
  .byte $18,$57,$00,$08,$00
  .byte $18,$58,$00,$10,$f8
  .byte $18,$42,$00,$18,$f0
.ifndef spritesheet_common_nomolos_fight_overlay0
spritesheet_common_nomolos_fight_overlay0:
.endif
  .byte $04
  .byte $01,$59,$01,$00,$08
  .byte $01,$5a,$01,$08,$00
  .byte $09,$42,$00,$00,$08
  .byte $09,$5b,$01,$08,$00
.ifndef spritesheet_common_nomolos_fight_overlay1
spritesheet_common_nomolos_fight_overlay1:
.endif
  .byte $04
  .byte $01,$5c,$01,$00,$08
  .byte $01,$5d,$01,$08,$00
  .byte $09,$5e,$01,$00,$08
  .byte $09,$5f,$01,$08,$00
.ifndef spritesheet_common_OneUp0
spritesheet_common_OneUp0:
.endif
  .byte $04
  .byte $00,$60,$00,$00,$08
  .byte $00,$60,$00,$08,$00
  .byte $08,$61,$00,$00,$08
  .byte $08,$62,$00,$08,$00
.ifndef spritesheet_common_NomolosUseFlail0
spritesheet_common_NomolosUseFlail0:
.endif
  .byte $0c
  .byte $00,$63,$00,$00,$08
  .byte $00,$64,$00,$08,$00
  .byte $00,$65,$00,$10,$f8
  .byte $08,$66,$00,$00,$08
  .byte $08,$67,$00,$08,$00
  .byte $08,$68,$00,$10,$f8
  .byte $10,$69,$00,$00,$08
  .byte $10,$6a,$00,$08,$00
  .byte $10,$6b,$00,$10,$f8
  .byte $18,$6c,$00,$00,$08
  .byte $18,$6d,$00,$08,$00
  .byte $18,$6e,$00,$10,$f8
.ifndef spritesheet_common_NomolosUseFlail1
spritesheet_common_NomolosUseFlail1:
.endif
  .byte $0c
  .byte $00,$6f,$00,$00,$08
  .byte $00,$64,$00,$08,$00
  .byte $00,$65,$00,$10,$f8
  .byte $08,$70,$00,$00,$08
  .byte $08,$67,$00,$08,$00
  .byte $08,$68,$00,$10,$f8
  .byte $10,$71,$00,$00,$08
  .byte $10,$72,$00,$08,$00
  .byte $10,$73,$00,$10,$f8
  .byte $18,$74,$00,$00,$08
  .byte $18,$75,$00,$08,$00
  .byte $18,$76,$00,$10,$f8
.ifndef spritesheet_common_FlailBall0
spritesheet_common_FlailBall0:
.endif
  .byte $01
  .byte $f0,$77,$00,$ea,$1e
.ifndef spritesheet_common_FlailBall1
spritesheet_common_FlailBall1:
.endif
  .byte $01
  .byte $ec,$77,$00,$00,$08
.ifndef spritesheet_common_FlailBall2
spritesheet_common_FlailBall2:
.endif
  .byte $01
  .byte $f0,$77,$00,$16,$f2
.ifndef spritesheet_common_FlailBall3
spritesheet_common_FlailBall3:
.endif
  .byte $01
  .byte $00,$77,$00,$1e,$ea
.ifndef spritesheet_common_FlailBall4
spritesheet_common_FlailBall4:
.endif
  .byte $01
  .byte $10,$77,$00,$16,$f2
.ifndef spritesheet_common_FlailBall5
spritesheet_common_FlailBall5:
.endif
  .byte $01
  .byte $14,$77,$00,$00,$08
.ifndef spritesheet_common_FlailBall6
spritesheet_common_FlailBall6:
.endif
  .byte $01
  .byte $10,$77,$00,$ea,$1e
.ifndef spritesheet_common_FlailBall7
spritesheet_common_FlailBall7:
.endif
  .byte $01
  .byte $00,$77,$00,$e2,$26
.ifndef spritesheet_common_nomolos_flail_overlay0
spritesheet_common_nomolos_flail_overlay0:
.endif
  .byte $04
  .byte $01,$59,$01,$03,$05
  .byte $01,$5a,$01,$0b,$fd
  .byte $09,$42,$00,$03,$05
  .byte $09,$5b,$01,$0b,$fd
.ifndef spritesheet_common_FlailItem0
spritesheet_common_FlailItem0:
.endif
  .byte $02
  .byte $00,$78,$00,$00,$08
  .byte $00,$79,$00,$08,$00
.ifndef spritesheet_common_NomolosUseSpear0
spritesheet_common_NomolosUseSpear0:
.endif
  .byte $0a
  .byte $f8,$7a,$00,$00,$08
  .byte $f8,$42,$00,$08,$00
  .byte $00,$7b,$00,$00,$08
  .byte $00,$44,$00,$08,$00
  .byte $08,$7c,$00,$00,$08
  .byte $08,$46,$00,$08,$00
  .byte $10,$7d,$00,$00,$08
  .byte $10,$48,$00,$08,$00
  .byte $18,$49,$00,$00,$08
  .byte $18,$4a,$00,$08,$00
.ifndef spritesheet_common_NomolosUseSpear1
spritesheet_common_NomolosUseSpear1:
.endif
  .byte $0c
  .byte $00,$4b,$00,$00,$08
  .byte $00,$4c,$00,$08,$00
  .byte $00,$4d,$00,$10,$f8
  .byte $08,$4e,$00,$00,$08
  .byte $08,$4f,$00,$08,$00
  .byte $08,$7e,$00,$10,$f8
  .byte $10,$52,$00,$00,$08
  .byte $10,$53,$00,$08,$00
  .byte $10,$7f,$00,$10,$f8
  .byte $18,$56,$00,$00,$08
  .byte $18,$57,$00,$08,$00
  .byte $18,$58,$00,$10,$f8
.ifndef spritesheet_common_Spear0
spritesheet_common_Spear0:
.endif
  .byte $03
  .byte $00,$80,$00,$00,$10
  .byte $00,$81,$00,$08,$08
  .byte $00,$82,$00,$10,$00
.ifndef spritesheet_common_Explosion0
spritesheet_common_Explosion0:
.endif
  .byte $04
  .byte $00,$00,$00,$00,$08
  .byte $00,$01,$00,$08,$00
  .byte $08,$02,$00,$00,$08
  .byte $08,$03,$00,$08,$00
.ifndef spritesheet_common_Explosion1
spritesheet_common_Explosion1:
.endif
  .byte $04
  .byte $00,$04,$00,$00,$08
  .byte $00,$05,$00,$08,$00
  .byte $08,$06,$00,$00,$08
  .byte $08,$07,$00,$08,$00
.ifndef spritesheet_common_Explosion2
spritesheet_common_Explosion2:
.endif
  .byte $04
  .byte $00,$08,$00,$00,$08
  .byte $00,$09,$00,$08,$00
  .byte $08,$0a,$00,$00,$08
  .byte $08,$0b,$00,$08,$00

