.ifndef SPRITESHEET2_SPRITES_IMPORTS_INC
SPRITESHEET2_SPRITES_IMPORTS_INC = 1

.global spritesheet2_FireGuy0
.global spritesheet2_FireGuy1
.global spritesheet2_Phoenix0
.global spritesheet2_Phoenix1
.global spritesheet2_Fireball0
.global spritesheet2_Fireball1
.global spritesheet2_Fireball2
.global spritesheet2_Snake0
.global spritesheet2_Snake1
.global spritesheet2_ThoguthMarch0
.global spritesheet2_ThoguthMarch1
.global spritesheet2_ThoguthMarch2
.global spritesheet2_ThoguthHammerfall0
.global spritesheet2_ThoguthHammerfall1
.global spritesheet2_ThoguthHammerfall2
.global spritesheet2_ThoguthLightning0
.global spritesheet2_ThoguthLightning1
.global spritesheet2_statue0
.global spritesheet2_statue1
.global spritesheet2_raven0
.global spritesheet2_raven1
.global spritesheet2_raven2
.global spritesheet2_sheep0
.global spritesheet2_sheep1
.global spritesheet2_sheep2
.global spritesheet2_bee0
.global spritesheet2_bee1
.global spritesheet2_bee2

.endif
