.include "spritesheet_common_animations_imports.inc"

;Animations
spritesheet_common_NomolosWalk:
  .byte $06
  .word spritesheet_common_NomolosWalk0
  .word spritesheet_common_NomolosWalk1
  .word spritesheet_common_NomolosWalk0
  .word spritesheet_common_NomolosWalk2
  .word $0000

spritesheet_common_nomolos_jump:
  .byte $0a
  .word spritesheet_common_nomolos_jump0
  .word $0000

spritesheet_common_nomolos_walk_overlay:
  .byte $0a
  .word spritesheet_common_nomolos_walk_overlay0
  .word spritesheet_common_nomolos_walk_overlay1
  .word spritesheet_common_nomolos_walk_overlay0
  .word spritesheet_common_nomolos_walk_overlay2
  .word $0000

spritesheet_common_nomolos_jump_overlay:
  .byte $0a
  .word spritesheet_common_nomolos_jump_overlay0
  .word $0000

spritesheet_common_Heart:
  .byte $0a
  .word spritesheet_common_Heart0
  .word $0000

spritesheet_common_Mouse:
  .byte $0a
  .word spritesheet_common_Mouse0
  .word $0000

spritesheet_common_nomolos_fight:
  .byte $06
  .word spritesheet_common_nomolos_fight0
  .word spritesheet_common_nomolos_fight1
  .word $0000

spritesheet_common_nomolos_fight_overlay:
  .byte $06
  .word spritesheet_common_nomolos_fight_overlay0
  .word spritesheet_common_nomolos_fight_overlay1
  .word $0000

spritesheet_common_NomolosUseFlail:
  .byte $06
  .word spritesheet_common_NomolosUseFlail0
  .word spritesheet_common_NomolosUseFlail1
  .word $0000

spritesheet_common_FlailBall:
  .byte $01
  .word spritesheet_common_FlailBall0
  .word spritesheet_common_FlailBall1
  .word spritesheet_common_FlailBall2
  .word spritesheet_common_FlailBall3
  .word spritesheet_common_FlailBall4
  .word spritesheet_common_FlailBall5
  .word spritesheet_common_FlailBall6
  .word spritesheet_common_FlailBall7
  .word $0000

spritesheet_common_nomolos_flail_overlay:
  .byte $06
  .word spritesheet_common_nomolos_flail_overlay0
  .word spritesheet_common_nomolos_flail_overlay0
  .word $0000

spritesheet_common_FlailItem:
  .byte $0a
  .word spritesheet_common_FlailItem0
  .word $0000

spritesheet_common_NomolosUseSpear:
  .byte $06
  .word spritesheet_common_NomolosUseSpear0
  .word spritesheet_common_NomolosUseSpear1
  .word $0000

spritesheet_common_SpearFly:
  .byte $0a
  .word spritesheet_common_Spear0
  .word $0000

spritesheet_common_Explosion:
  .byte 3
  .word spritesheet_common_Explosion2
  .word spritesheet_common_Explosion1
  .word spritesheet_common_Explosion0
  .word $0000