;Meta Sprite Table
.export spritesheet2_NomolosWalk0
spritesheet2_NomolosWalk0:
  .byte $08
  .byte $00,$00,$01,$00,$08
  .byte $00,$01,$01,$08,$00
  .byte $08,$02,$01,$00,$08
  .byte $08,$03,$01,$08,$00
  .byte $10,$04,$01,$00,$08
  .byte $10,$05,$01,$08,$00
  .byte $18,$06,$01,$00,$08
  .byte $18,$07,$01,$08,$00
.export spritesheet2_NomolosWalk1
spritesheet2_NomolosWalk1:
  .byte $08
  .byte $00,$08,$01,$00,$08
  .byte $00,$09,$01,$08,$00
  .byte $08,$0a,$00,$00,$08
  .byte $08,$0b,$01,$08,$00
  .byte $10,$0c,$01,$00,$08
  .byte $10,$0d,$01,$08,$00
  .byte $18,$0e,$01,$00,$08
  .byte $18,$0f,$01,$08,$00
.export spritesheet2_NomolosWalk2
spritesheet2_NomolosWalk2:
  .byte $08
  .byte $00,$10,$01,$00,$08
  .byte $00,$11,$01,$08,$00
  .byte $08,$12,$01,$00,$08
  .byte $08,$13,$01,$08,$00
  .byte $10,$14,$01,$00,$08
  .byte $10,$15,$01,$08,$00
  .byte $18,$16,$01,$00,$08
  .byte $18,$17,$01,$08,$00
.export spritesheet2_NomolosJump0
spritesheet2_NomolosJump0:
  .byte $08
  .byte $00,$18,$01,$00,$08
  .byte $00,$19,$01,$08,$00
  .byte $08,$1a,$01,$00,$08
  .byte $08,$1b,$01,$08,$00
  .byte $10,$1c,$01,$00,$08
  .byte $10,$1d,$01,$08,$00
  .byte $18,$1e,$01,$00,$08
  .byte $18,$1f,$01,$08,$00
.export spritesheet2_NomolosWalkOverlay0
spritesheet2_NomolosWalkOverlay0:
  .byte $04
  .byte $01,$20,$00,$00,$08
  .byte $01,$21,$00,$08,$00
  .byte $09,$22,$00,$00,$08
  .byte $09,$23,$00,$08,$00
.export spritesheet2_NomolosWalkOverlay1
spritesheet2_NomolosWalkOverlay1:
  .byte $04
  .byte $01,$24,$00,$00,$08
  .byte $01,$25,$00,$08,$00
  .byte $09,$26,$00,$00,$08
  .byte $09,$27,$00,$08,$00
.export spritesheet2_NomolosWalkOverlay2
spritesheet2_NomolosWalkOverlay2:
  .byte $04
  .byte $01,$24,$00,$00,$08
  .byte $01,$28,$00,$08,$00
  .byte $09,$26,$00,$00,$08
  .byte $09,$27,$00,$08,$00
.export spritesheet2_NomolosJumpOverlay0
spritesheet2_NomolosJumpOverlay0:
  .byte $04
  .byte $01,$20,$00,$00,$08
  .byte $01,$29,$00,$08,$00
  .byte $09,$22,$00,$00,$08
  .byte $09,$23,$00,$08,$00
.export spritesheet2_Heart0
spritesheet2_Heart0:
  .byte $01
  .byte $00,$2a,$00,$00,$00
.export spritesheet2_Mouse0
spritesheet2_Mouse0:
  .byte $02
  .byte $00,$2b,$00,$00,$08
  .byte $00,$2c,$00,$08,$00
.export spritesheet2_SlumpedArmor0
spritesheet2_SlumpedArmor0:
  .byte $06
  .byte $08,$2d,$00,$00,$08
  .byte $08,$2e,$00,$08,$00
  .byte $10,$2f,$01,$00,$08
  .byte $10,$30,$01,$08,$00
  .byte $18,$31,$01,$00,$08
  .byte $18,$32,$01,$08,$00
.export spritesheet2_SlumpedArmorOverlay0
spritesheet2_SlumpedArmorOverlay0:
  .byte $02
  .byte $08,$33,$00,$00,$00
  .byte $10,$34,$00,$00,$00
.export spritesheet2_ScardyCat0
spritesheet2_ScardyCat0:
  .byte $08
  .byte $00,$35,$01,$00,$08
  .byte $00,$36,$01,$08,$00
  .byte $08,$37,$01,$00,$08
  .byte $08,$38,$01,$08,$00
  .byte $10,$39,$01,$00,$08
  .byte $10,$3a,$01,$08,$00
  .byte $18,$3b,$01,$00,$08
  .byte $18,$3c,$01,$08,$00
.export spritesheet2_ScardyCatOverlay0
spritesheet2_ScardyCatOverlay0:
  .byte $04
  .byte $08,$3d,$00,$00,$08
  .byte $08,$3e,$00,$08,$00
  .byte $10,$3f,$00,$00,$08
  .byte $10,$40,$00,$08,$00
.export spritesheet2_NomolosFight0
spritesheet2_NomolosFight0:
  .byte $0a
  .byte $f8,$41,$01,$00,$08
  .byte $f8,$42,$00,$08,$00
  .byte $00,$43,$01,$00,$08
  .byte $00,$44,$01,$08,$00
  .byte $08,$45,$01,$00,$08
  .byte $08,$46,$01,$08,$00
  .byte $10,$47,$01,$00,$08
  .byte $10,$48,$01,$08,$00
  .byte $18,$49,$01,$00,$08
  .byte $18,$4a,$01,$08,$00
.export spritesheet2_NomolosFight1
spritesheet2_NomolosFight1:
  .byte $10
  .byte $00,$4b,$01,$00,$08
  .byte $00,$4c,$01,$08,$00
  .byte $00,$4d,$00,$10,$f8
  .byte $00,$42,$00,$18,$f0
  .byte $08,$4e,$01,$00,$08
  .byte $08,$4f,$01,$08,$00
  .byte $08,$50,$01,$10,$f8
  .byte $08,$51,$01,$18,$f0
  .byte $10,$52,$01,$00,$08
  .byte $10,$53,$01,$08,$00
  .byte $10,$54,$01,$10,$f8
  .byte $10,$55,$01,$18,$f0
  .byte $18,$56,$01,$00,$08
  .byte $18,$57,$01,$08,$00
  .byte $18,$58,$01,$10,$f8
  .byte $18,$42,$00,$18,$f0
.export spritesheet2_NomolosFightOverlay0
spritesheet2_NomolosFightOverlay0:
  .byte $04
  .byte $01,$59,$00,$00,$08
  .byte $01,$5a,$00,$08,$00
  .byte $09,$42,$00,$00,$08
  .byte $09,$5b,$00,$08,$00
.export spritesheet2_NomolosFightOverlay1
spritesheet2_NomolosFightOverlay1:
  .byte $04
  .byte $01,$5c,$00,$00,$08
  .byte $01,$5d,$00,$08,$00
  .byte $09,$5e,$00,$00,$08
  .byte $09,$5f,$00,$08,$00
.export spritesheet2_OneUp0
spritesheet2_OneUp0:
  .byte $04
  .byte $00,$60,$00,$00,$08
  .byte $00,$60,$00,$08,$00
  .byte $08,$61,$01,$00,$08
  .byte $08,$62,$01,$08,$00
.export spritesheet2_NomolosUseFlail0
spritesheet2_NomolosUseFlail0:
  .byte $0c
  .byte $00,$63,$01,$00,$08
  .byte $00,$64,$01,$08,$00
  .byte $00,$65,$01,$10,$f8
  .byte $08,$66,$01,$00,$08
  .byte $08,$67,$01,$08,$00
  .byte $08,$68,$01,$10,$f8
  .byte $10,$69,$01,$00,$08
  .byte $10,$6a,$01,$08,$00
  .byte $10,$6b,$01,$10,$f8
  .byte $18,$6c,$01,$00,$08
  .byte $18,$6d,$01,$08,$00
  .byte $18,$6e,$01,$10,$f8
.export spritesheet2_NomolosUseFlail1
spritesheet2_NomolosUseFlail1:
  .byte $0c
  .byte $00,$6f,$01,$00,$08
  .byte $00,$64,$01,$08,$00
  .byte $00,$65,$01,$10,$f8
  .byte $08,$70,$01,$00,$08
  .byte $08,$67,$01,$08,$00
  .byte $08,$68,$01,$10,$f8
  .byte $10,$71,$01,$00,$08
  .byte $10,$72,$01,$08,$00
  .byte $10,$73,$01,$10,$f8
  .byte $18,$74,$01,$00,$08
  .byte $18,$75,$01,$08,$00
  .byte $18,$76,$01,$10,$f8
.export spritesheet2_FlailBall0
spritesheet2_FlailBall0:
  .byte $01
  .byte $f0,$77,$01,$ea,$16
.export spritesheet2_FlailBall1
spritesheet2_FlailBall1:
  .byte $01
  .byte $ec,$77,$01,$00,$00
.export spritesheet2_FlailBall2
spritesheet2_FlailBall2:
  .byte $01
  .byte $f0,$77,$01,$16,$ea
.export spritesheet2_FlailBall3
spritesheet2_FlailBall3:
  .byte $01
  .byte $00,$77,$01,$28,$d8
.export spritesheet2_FlailBall4
spritesheet2_FlailBall4:
  .byte $01
  .byte $10,$77,$01,$16,$ea
.export spritesheet2_FlailBall5
spritesheet2_FlailBall5:
  .byte $01
  .byte $14,$77,$01,$00,$00
.export spritesheet2_FlailBall6
spritesheet2_FlailBall6:
  .byte $01
  .byte $10,$77,$01,$ea,$16
.export spritesheet2_FlailBall7
spritesheet2_FlailBall7:
  .byte $01
  .byte $00,$77,$01,$d8,$28
.export spritesheet2_NomolosFlailOverlay0
spritesheet2_NomolosFlailOverlay0:
  .byte $04
  .byte $01,$59,$00,$03,$05
  .byte $01,$5a,$00,$0b,$fd
  .byte $09,$42,$00,$03,$05
  .byte $09,$5b,$00,$0b,$fd
.export spritesheet2_FlailItem0
spritesheet2_FlailItem0:
  .byte $02
  .byte $00,$78,$01,$00,$08
  .byte $00,$79,$01,$08,$00
.export spritesheet2_NomolosUseSpear0
spritesheet2_NomolosUseSpear0:
  .byte $0a
  .byte $f8,$7a,$01,$00,$08
  .byte $f8,$42,$00,$08,$00
  .byte $00,$7b,$01,$00,$08
  .byte $00,$44,$01,$08,$00
  .byte $08,$7c,$01,$00,$08
  .byte $08,$46,$01,$08,$00
  .byte $10,$7d,$01,$00,$08
  .byte $10,$48,$01,$08,$00
  .byte $18,$49,$01,$00,$08
  .byte $18,$4a,$01,$08,$00
.export spritesheet2_NomolosUseSpear1
spritesheet2_NomolosUseSpear1:
  .byte $0c
  .byte $00,$4b,$01,$00,$08
  .byte $00,$4c,$01,$08,$00
  .byte $00,$4d,$00,$10,$f8
  .byte $08,$4e,$01,$00,$08
  .byte $08,$4f,$01,$08,$00
  .byte $08,$7e,$01,$10,$f8
  .byte $10,$52,$01,$00,$08
  .byte $10,$53,$01,$08,$00
  .byte $10,$7f,$01,$10,$f8
  .byte $18,$56,$01,$00,$08
  .byte $18,$57,$01,$08,$00
  .byte $18,$58,$01,$10,$f8
.export spritesheet2_Spear0
spritesheet2_Spear0:
  .byte $03
  .byte $00,$80,$00,$00,$10
  .byte $00,$81,$01,$08,$08
  .byte $00,$82,$01,$10,$00
.export spritesheet2_Deentle0
spritesheet2_Deentle0:
  .byte $04
  .byte $00,$00,$02,$00,$08
  .byte $00,$01,$02,$08,$00
  .byte $08,$02,$02,$00,$08
  .byte $08,$03,$02,$08,$00
.export spritesheet2_Deentle1
spritesheet2_Deentle1:
  .byte $04
  .byte $00,$04,$02,$00,$08
  .byte $00,$05,$02,$08,$00
  .byte $08,$06,$02,$00,$08
  .byte $08,$07,$02,$08,$00
.export spritesheet2_Explosion0
spritesheet2_Explosion0:
  .byte $04
  .byte $00,$00,$01,$00,$08
  .byte $00,$01,$01,$08,$00
  .byte $08,$02,$01,$00,$08
  .byte $08,$03,$01,$08,$00
.export spritesheet2_Explosion1
spritesheet2_Explosion1:
  .byte $04
  .byte $00,$04,$01,$00,$08
  .byte $00,$05,$01,$08,$00
  .byte $08,$06,$01,$00,$08
  .byte $08,$07,$01,$08,$00
.export spritesheet2_Explosion2
spritesheet2_Explosion2:
  .byte $04
  .byte $00,$08,$01,$00,$08
  .byte $00,$09,$01,$08,$00
  .byte $08,$0a,$01,$00,$08
  .byte $08,$0b,$01,$08,$00
.export spritesheet2_Beedie0
spritesheet2_Beedie0:
  .byte $04
  .byte $00,$00,$00,$00,$08
  .byte $00,$01,$00,$08,$00
  .byte $08,$02,$00,$00,$08
  .byte $08,$03,$00,$08,$00
.export spritesheet2_Beedie1
spritesheet2_Beedie1:
  .byte $04
  .byte $00,$04,$00,$00,$08
  .byte $00,$05,$00,$08,$00
  .byte $08,$06,$00,$00,$08
  .byte $08,$07,$00,$08,$00
.export spritesheet2_Grank0
spritesheet2_Grank0:
  .byte $04
  .byte $00,$00,$02,$00,$08
  .byte $00,$01,$02,$08,$00
  .byte $08,$02,$02,$00,$08
  .byte $08,$03,$02,$08,$00
.export spritesheet2_Grank1
spritesheet2_Grank1:
  .byte $04
  .byte $00,$04,$02,$00,$08
  .byte $00,$05,$02,$08,$00
  .byte $08,$06,$02,$00,$08
  .byte $08,$07,$02,$08,$00
.export spritesheet2_Skelekin0
spritesheet2_Skelekin0:
  .byte $08
  .byte $00,$00,$01,$00,$08
  .byte $00,$9b,$00,$08,$00
  .byte $08,$01,$01,$00,$08
  .byte $08,$02,$01,$08,$00
  .byte $10,$03,$01,$00,$08
  .byte $10,$04,$01,$08,$00
  .byte $18,$05,$01,$00,$08
  .byte $18,$06,$01,$08,$00
.export spritesheet2_Skelekin1
spritesheet2_Skelekin1:
  .byte $08
  .byte $00,$00,$01,$00,$08
  .byte $00,$9b,$00,$08,$00
  .byte $08,$01,$01,$00,$08
  .byte $08,$07,$01,$08,$00
  .byte $10,$08,$01,$00,$08
  .byte $10,$9b,$00,$08,$00
  .byte $18,$05,$01,$00,$08
  .byte $18,$9b,$00,$08,$00
.export spritesheet2_Skelekin2
spritesheet2_Skelekin2:
  .byte $08
  .byte $00,$00,$01,$00,$08
  .byte $00,$9b,$00,$08,$00
  .byte $08,$09,$01,$00,$08
  .byte $08,$0a,$01,$08,$00
  .byte $10,$0b,$01,$00,$08
  .byte $10,$04,$01,$08,$00
  .byte $18,$05,$01,$00,$08
  .byte $18,$06,$01,$08,$00
.export spritesheet2_Bat0
spritesheet2_Bat0:
  .byte $02
  .byte $00,$00,$00,$00,$08
  .byte $00,$01,$00,$08,$00
.export spritesheet2_Bat1
spritesheet2_Bat1:
  .byte $02
  .byte $00,$02,$00,$00,$08
  .byte $00,$03,$00,$08,$00

