.ifndef SPRITESHEET2_PATTERNS_IMPORTS_INC
SPRITESHEET2_PATTERNS_IMPORTS_INC = 1

.global spritesheet2_FireGuy_chr
.global spritesheet2_Phoenix_chr
.global spritesheet2_Fireball_chr
.global spritesheet2_Snake_chr
.global spritesheet2_Thoguth_chr
.global spritesheet2_statue_chr
.global spritesheet2_raven_chr
.global spritesheet2_sheep_chr
.global spritesheet2_bee_chr
.global spritesheet2_Gort_chr
.global spritesheet2_Hippocritter_chr
.global spritesheet2_ArmoredSkelekin_chr
.global spritesheet2_Attacknid_chr
.global spritesheet2_Laser_chr
.global spritesheet2_Sneep_chr

.endif