.include "spritesheet2_animations_imports.inc"

spritesheet2_PhoenixFly:
  .byte $0a
  .word spritesheet2_Phoenix0
  .word spritesheet2_Phoenix1
  .word $0000

spritesheet2_FireballFly:
  .byte $02
  .word spritesheet2_Fireball2
  .word spritesheet2_Fireball1
  .word spritesheet2_Fireball0
  .word spritesheet2_Fireball1
  .word $0000

spritesheet2_SnakeSlither:
  .byte $14
  .word spritesheet2_Snake0
  .word spritesheet2_Snake1
  .word $0000

spritesheet2_raven_fly:
  .byte $0a
  .word spritesheet2_raven1
  .word spritesheet2_raven2
  .word $0000

spritesheet2_SheepButt:
  .byte $0a
  .word spritesheet2_sheep0
  .word spritesheet2_sheep1
  .word spritesheet2_sheep2
  .word $0000

spritesheet2_BeeFly:
  .byte $02
  .word spritesheet2_bee1
  .word spritesheet2_bee2
  .word $0000

spritesheet2_ArmoredSkelekinWalk:
  .byte $0a
  .word spritesheet2_ArmoredSkelekin1
  .word spritesheet2_ArmoredSkelekin0
  .word spritesheet2_ArmoredSkelekin1
  .word spritesheet2_ArmoredSkelekin2
  .word $0000

spritesheet2_AttacknidClimb:
  .byte $0a
  .word spritesheet2_Attacknid1
  .word spritesheet2_Attacknid0
  .word $0000

spritesheet2_SneepRun:
  .byte $0a
  .word spritesheet2_SneepRun1
  .word spritesheet2_SneepRun0
  .word spritesheet2_SneepRun1
  .word spritesheet2_SneepRun2
  .word $0000

spritesheet2_SneepEyeRun:
  .byte $0a
  .word spritesheet2_SneepEyeRun1
  .word spritesheet2_SneepEyeRun0
  .word spritesheet2_SneepEyeRun1
  .word spritesheet2_SneepEyeRun2
  .word $0000

spritesheet2_SneepFlap:
  .byte $0a
  .word spritesheet2_SneepFlap0
  .word spritesheet2_SneepFlap1
  .word $0000

spritesheet2_SneepEyeFlap:
  .byte $0a
  .word spritesheet2_SneepEyeFlap0
  .word spritesheet2_SneepEyeFlap1
  .word $0000
