.include "spritesheet_common_sprites_imports.inc"

;Meta Sprite Table
.ifndef spritesheet_common_NomolosWalk0
spritesheet_common_NomolosWalk0:
.endif
  .byte $08
  .byte $fc,$00,$00,$fe,$06
  .byte $fc,$01,$00,$06,$fe
  .byte $04,$02,$00,$fe,$06
  .byte $04,$03,$00,$06,$fe
  .byte $0c,$04,$00,$fe,$06
  .byte $0c,$05,$00,$06,$fe
  .byte $14,$06,$00,$fe,$06
  .byte $14,$07,$00,$06,$fe
.ifndef spritesheet_common_NomolosWalk1
spritesheet_common_NomolosWalk1:
.endif
  .byte $08
  .byte $fc,$08,$00,$fe,$06
  .byte $fc,$09,$00,$06,$fe
  .byte $04,$0a,$00,$fe,$06
  .byte $04,$0b,$00,$06,$fe
  .byte $0c,$0c,$00,$fe,$06
  .byte $0c,$0d,$00,$06,$fe
  .byte $14,$0e,$00,$fe,$06
  .byte $14,$0f,$00,$06,$fe
.ifndef spritesheet_common_NomolosWalk2
spritesheet_common_NomolosWalk2:
.endif
  .byte $08
  .byte $fc,$10,$00,$fe,$06
  .byte $fc,$11,$00,$06,$fe
  .byte $04,$12,$00,$fe,$06
  .byte $04,$13,$00,$06,$fe
  .byte $0c,$14,$00,$fe,$06
  .byte $0c,$15,$00,$06,$fe
  .byte $14,$16,$00,$fe,$06
  .byte $14,$17,$00,$06,$fe
.ifndef spritesheet_common_nomolos_jump0
spritesheet_common_nomolos_jump0:
.endif
  .byte $08
  .byte $fc,$18,$00,$fe,$06
  .byte $fc,$19,$00,$06,$fe
  .byte $04,$1a,$00,$fe,$06
  .byte $04,$1b,$00,$06,$fe
  .byte $0c,$1c,$00,$fe,$06
  .byte $0c,$1d,$00,$06,$fe
  .byte $14,$1e,$00,$fe,$06
  .byte $14,$1f,$00,$06,$fe
.ifndef spritesheet_common_nomolos_walk_overlay0
spritesheet_common_nomolos_walk_overlay0:
.endif
  .byte $04
  .byte $fd,$20,$01,$fe,$06
  .byte $fd,$21,$01,$06,$fe
  .byte $05,$22,$01,$fe,$06
  .byte $05,$23,$01,$06,$fe
.ifndef spritesheet_common_nomolos_walk_overlay1
spritesheet_common_nomolos_walk_overlay1:
.endif
  .byte $04
  .byte $fd,$24,$01,$fe,$06
  .byte $fd,$25,$01,$06,$fe
  .byte $05,$26,$01,$fe,$06
  .byte $05,$27,$01,$06,$fe
.ifndef spritesheet_common_nomolos_walk_overlay2
spritesheet_common_nomolos_walk_overlay2:
.endif
  .byte $04
  .byte $fd,$24,$01,$fe,$06
  .byte $fd,$28,$01,$06,$fe
  .byte $05,$26,$01,$fe,$06
  .byte $05,$27,$01,$06,$fe
.ifndef spritesheet_common_nomolos_jump_overlay0
spritesheet_common_nomolos_jump_overlay0:
.endif
  .byte $04
  .byte $fd,$20,$01,$fe,$06
  .byte $fd,$29,$01,$06,$fe
  .byte $05,$22,$01,$fe,$06
  .byte $05,$23,$01,$06,$fe
.ifndef spritesheet_common_Heart0
spritesheet_common_Heart0:
.endif
  .byte $01
  .byte $00,$2a,$01,$00,$00
.ifndef spritesheet_common_Mouse0
spritesheet_common_Mouse0:
.endif
  .byte $02
  .byte $00,$2b,$01,$00,$08
  .byte $00,$2c,$00,$08,$00
.ifndef spritesheet_common_SlumpedArmor0
spritesheet_common_SlumpedArmor0:
.endif
  .byte $06
  .byte $04,$2d,$00,$fe,$06
  .byte $04,$2e,$00,$06,$fe
  .byte $0c,$2f,$00,$fe,$06
  .byte $0c,$30,$00,$06,$fe
  .byte $14,$31,$00,$fe,$06
  .byte $14,$32,$00,$06,$fe
.ifndef spritesheet_common_SlumpedArmorOverlay0
spritesheet_common_SlumpedArmorOverlay0:
.endif
  .byte $02
  .byte $04,$33,$01,$fe,$fe
  .byte $0c,$34,$01,$fe,$fe
.ifndef spritesheet_common_ScardyCat0
spritesheet_common_ScardyCat0:
.endif
  .byte $08
  .byte $fc,$35,$00,$fe,$06
  .byte $fc,$36,$00,$06,$fe
  .byte $04,$37,$00,$fe,$06
  .byte $04,$38,$00,$06,$fe
  .byte $0c,$39,$00,$fe,$06
  .byte $0c,$3a,$00,$06,$fe
  .byte $14,$3b,$00,$fe,$06
  .byte $14,$3c,$00,$06,$fe
.ifndef spritesheet_common_ScardyCatOverlay0
spritesheet_common_ScardyCatOverlay0:
.endif
  .byte $04
  .byte $04,$3d,$01,$fe,$07
  .byte $04,$3e,$01,$06,$ff
  .byte $0c,$3f,$01,$fe,$07
  .byte $0c,$40,$01,$06,$ff
.ifndef spritesheet_common_nomolos_fight0
spritesheet_common_nomolos_fight0:
.endif
  .byte $0a
  .byte $f4,$41,$00,$fe,$06
  .byte $f4,$42,$00,$06,$fe
  .byte $fc,$43,$00,$fe,$06
  .byte $fc,$44,$00,$06,$fe
  .byte $04,$45,$00,$fe,$06
  .byte $04,$46,$00,$06,$fe
  .byte $0c,$47,$00,$fe,$06
  .byte $0c,$48,$00,$06,$fe
  .byte $14,$49,$00,$fe,$06
  .byte $14,$4a,$00,$06,$fe
.ifndef spritesheet_common_nomolos_fight1
spritesheet_common_nomolos_fight1:
.endif
  .byte $10
  .byte $fc,$4b,$00,$fe,$06
  .byte $fc,$4c,$00,$06,$fe
  .byte $fc,$4d,$00,$0e,$f6
  .byte $fc,$42,$00,$16,$ee
  .byte $04,$4e,$00,$fe,$06
  .byte $04,$4f,$00,$06,$fe
  .byte $04,$50,$00,$0e,$f6
  .byte $04,$51,$00,$16,$ee
  .byte $0c,$52,$00,$fe,$06
  .byte $0c,$53,$00,$06,$fe
  .byte $0c,$54,$00,$0e,$f6
  .byte $0c,$55,$00,$16,$ee
  .byte $14,$56,$00,$fe,$06
  .byte $14,$57,$00,$06,$fe
  .byte $14,$58,$00,$0e,$f6
  .byte $14,$42,$00,$16,$ee
.ifndef spritesheet_common_nomolos_fight_overlay0
spritesheet_common_nomolos_fight_overlay0:
.endif
  .byte $04
  .byte $fd,$59,$01,$fe,$06
  .byte $fd,$5a,$01,$06,$fe
  .byte $05,$42,$00,$fe,$06
  .byte $05,$5b,$01,$06,$fe
.ifndef spritesheet_common_nomolos_fight_overlay1
spritesheet_common_nomolos_fight_overlay1:
.endif
  .byte $04
  .byte $fd,$5c,$01,$fe,$06
  .byte $fd,$5d,$01,$06,$fe
  .byte $05,$5e,$01,$fe,$06
  .byte $05,$5f,$01,$06,$fe
.ifndef spritesheet_common_OneUp0
spritesheet_common_OneUp0:
.endif
  .byte $04
  .byte $00,$60,$00,$00,$08
  .byte $00,$60,$00,$08,$00
  .byte $08,$61,$00,$00,$08
  .byte $08,$62,$00,$08,$00
.ifndef spritesheet_common_NomolosUseFlail0
spritesheet_common_NomolosUseFlail0:
.endif
  .byte $0c
  .byte $fc,$63,$00,$fe,$06
  .byte $fc,$64,$00,$06,$fe
  .byte $fc,$65,$00,$0e,$f6
  .byte $04,$66,$00,$fe,$06
  .byte $04,$67,$00,$06,$fe
  .byte $04,$68,$00,$0e,$f6
  .byte $0c,$69,$00,$fe,$06
  .byte $0c,$6a,$00,$06,$fe
  .byte $0c,$6b,$00,$0e,$f6
  .byte $14,$6c,$00,$fe,$06
  .byte $14,$6d,$00,$06,$fe
  .byte $14,$6e,$00,$0e,$f6
.ifndef spritesheet_common_NomolosUseFlail1
spritesheet_common_NomolosUseFlail1:
.endif
  .byte $0c
  .byte $fc,$6f,$00,$fe,$06
  .byte $fc,$64,$00,$06,$fe
  .byte $fc,$65,$00,$0e,$f6
  .byte $04,$70,$00,$fe,$06
  .byte $04,$67,$00,$06,$fe
  .byte $04,$68,$00,$0e,$f6
  .byte $0c,$71,$00,$fe,$06
  .byte $0c,$72,$00,$06,$fe
  .byte $0c,$73,$00,$0e,$f6
  .byte $14,$74,$00,$fe,$06
  .byte $14,$75,$00,$06,$fe
  .byte $14,$76,$00,$0e,$f6
.ifndef spritesheet_common_FlailBall0
spritesheet_common_FlailBall0:
.endif
  .byte $01
  .byte $ec,$77,$00,$e8,$1c
.ifndef spritesheet_common_FlailBall1
spritesheet_common_FlailBall1:
.endif
  .byte $01
  .byte $e8,$77,$00,$fe,$06
.ifndef spritesheet_common_FlailBall2
spritesheet_common_FlailBall2:
.endif
  .byte $01
  .byte $ec,$77,$00,$14,$f0
.ifndef spritesheet_common_FlailBall3
spritesheet_common_FlailBall3:
.endif
  .byte $01
  .byte $fc,$77,$00,$1c,$e8
.ifndef spritesheet_common_FlailBall4
spritesheet_common_FlailBall4:
.endif
  .byte $01
  .byte $0c,$77,$00,$14,$f0
.ifndef spritesheet_common_FlailBall5
spritesheet_common_FlailBall5:
.endif
  .byte $01
  .byte $10,$77,$00,$fe,$06
.ifndef spritesheet_common_FlailBall6
spritesheet_common_FlailBall6:
.endif
  .byte $01
  .byte $0c,$77,$00,$e8,$1c
.ifndef spritesheet_common_FlailBall7
spritesheet_common_FlailBall7:
.endif
  .byte $01
  .byte $fc,$77,$00,$e0,$24
.ifndef spritesheet_common_nomolos_flail_overlay0
spritesheet_common_nomolos_flail_overlay0:
.endif
  .byte $04
  .byte $fd,$59,$01,$01,$03
  .byte $fd,$5a,$01,$09,$fb
  .byte $05,$42,$00,$01,$03
  .byte $05,$5b,$01,$09,$fb
.ifndef spritesheet_common_FlailItem0
spritesheet_common_FlailItem0:
.endif
  .byte $02
  .byte $00,$78,$00,$00,$08
  .byte $00,$79,$00,$08,$00
.ifndef spritesheet_common_NomolosUseSpear0
spritesheet_common_NomolosUseSpear0:
.endif
  .byte $0a
  .byte $f4,$7a,$00,$fe,$06
  .byte $f4,$42,$00,$06,$fe
  .byte $fc,$7b,$00,$fe,$06
  .byte $fc,$44,$00,$06,$fe
  .byte $04,$7c,$00,$fe,$06
  .byte $04,$46,$00,$06,$fe
  .byte $0c,$7d,$00,$fe,$06
  .byte $0c,$48,$00,$06,$fe
  .byte $14,$49,$00,$fe,$06
  .byte $14,$4a,$00,$06,$fe
.ifndef spritesheet_common_NomolosUseSpear1
spritesheet_common_NomolosUseSpear1:
.endif
  .byte $0c
  .byte $fc,$4b,$00,$fe,$06
  .byte $fc,$4c,$00,$06,$fe
  .byte $fc,$4d,$00,$0e,$f6
  .byte $04,$4e,$00,$fe,$06
  .byte $04,$4f,$00,$06,$fe
  .byte $04,$7e,$00,$0e,$f6
  .byte $0c,$52,$00,$fe,$06
  .byte $0c,$53,$00,$06,$fe
  .byte $0c,$7f,$00,$0e,$f6
  .byte $14,$56,$00,$fe,$06
  .byte $14,$57,$00,$06,$fe
  .byte $14,$58,$00,$0e,$f6
.ifndef spritesheet_common_Spear0
spritesheet_common_Spear0:
.endif
  .byte $03
  .byte $00,$80,$00,$00,$10
  .byte $00,$81,$00,$08,$08
  .byte $00,$82,$00,$10,$00
.ifndef spritesheet_common_Explosion0
spritesheet_common_Explosion0:
.endif
  .byte $04
  .byte $00,$00,$00,$00,$08
  .byte $00,$01,$00,$08,$00
  .byte $08,$02,$00,$00,$08
  .byte $08,$03,$00,$08,$00
.ifndef spritesheet_common_Explosion1
spritesheet_common_Explosion1:
.endif
  .byte $04
  .byte $00,$04,$00,$00,$08
  .byte $00,$05,$00,$08,$00
  .byte $08,$06,$00,$00,$08
  .byte $08,$07,$00,$08,$00
.ifndef spritesheet_common_Explosion2
spritesheet_common_Explosion2:
.endif
  .byte $04
  .byte $00,$08,$00,$00,$08
  .byte $00,$09,$00,$08,$00
  .byte $08,$0a,$00,$00,$08
  .byte $08,$0b,$00,$08,$00
.ifndef spritesheet_common_Bat0
spritesheet_common_Bat0:
.endif
  .byte $02
  .byte $00,$00,$01,$00,$08
  .byte $00,$01,$01,$08,$00
.ifndef spritesheet_common_Bat1
spritesheet_common_Bat1:
.endif
  .byte $02
  .byte $00,$02,$01,$00,$08
  .byte $00,$03,$01,$08,$00
