.ifndef SPRITESHEET1_PATTERNS_IMPORTS_INC
SPRITESHEET1_PATTERNS_IMPORTS_INC = 1

.global spritesheet1_Deentle_chr
.global spritesheet1_Beedie_chr
.global spritesheet1_Grank_chr
.global spritesheet1_Skelekin_chr
.global spritesheet1_Snuffer_chr
.global spritesheet1_Owl_chr
.global spritesheet1_Batree_chr
.global spritesheet1_Snail_chr
.global spritesheet1_Dragon_chr
.global spritesheet1_IceBall_chr
.global spritesheet1_Shark_chr
.global spritesheet1_Stalactite_chr
.global spritesheet1_DragonFace_chr
.global spritesheet1_GrubselimBoj_chr
.global spritesheet1_bigfireball_chr
.global spritesheet1_Boulder_chr

.endif