.include "spritesheet2_animations_imports.inc"

spritesheet2_PhoenixFly:
  .byte $0a
  .word spritesheet2_Phoenix0
  .word spritesheet2_Phoenix1
  .word $0000

spritesheet2_FireballFly:
  .byte $02
  .word spritesheet2_Fireball2
  .word spritesheet2_Fireball1
  .word spritesheet2_Fireball0
  .word spritesheet2_Fireball1
  .word $0000

spritesheet2_SnakeSlither:
  .byte $14
  .word spritesheet2_Snake0
  .word spritesheet2_Snake1
  .word $0000

spritesheet2_ThoguthMarch:
  .byte $0a
  .word spritesheet2_ThoguthMarch0
  .word spritesheet2_ThoguthMarch1
  .word spritesheet2_ThoguthMarch0
  .word spritesheet2_ThoguthMarch2
  .word $0000

spritesheet2_ThoguthHammerfall:
  .byte 20
  .word spritesheet2_ThoguthHammerfall0
  .word spritesheet2_ThoguthHammerfall1
  .word spritesheet2_ThoguthHammerfall2
  .word $0000

spritesheet2_ThoguthLightning:
  .byte $03
  .word spritesheet2_ThoguthLightning0
  .word spritesheet2_ThoguthLightning1
  .word $0000

spritesheet2_raven_fly:
  .byte $0a
  .word spritesheet2_raven1
  .word spritesheet2_raven2
  .word $0000

spritesheet2_SheepButt:
  .byte $0a
  .word spritesheet2_sheep0
  .word spritesheet2_sheep1
  .word spritesheet2_sheep2
  .word $0000

spritesheet2_BeeFly:
  .byte $0a
  .word spritesheet2_bee1
  .word spritesheet2_bee2
  .word $0000

