.ifndef SPRITESHEET1_ANIMATIONS_IMPORTS_INC
SPRITESHEET1_ANIMATIONS_IMPORTS_INC = 1

.global spritesheet1_DeentleWalk
.global spritesheet1_BeedieBlob
.global spritesheet1_GrankFly
.global spritesheet1_Batree
.global spritesheet1_OwlFly
.global spritesheet1_OwlAttack
.global spritesheet1_SnufferRun
.global spritesheet1_SnufferBite
.global spritesheet1_SkelekinWalk
.global spritesheet1_SnailCrawl
.global spritesheet1_DragonFly
.global spritesheet1_IceBallFly
.global spritesheet1_SharkLeap
.global spritesheet1_bigfireballfly
.global spritesheet1_ThoguthMarch
.global spritesheet1_ThoguthHammerfall
.global spritesheet1_ThoguthLightning
.global spritesheet1_SnowWalk
.global spritesheet1_SnowWalkOverlay

.endif
