.ifndef LEVELDATAINDEX_INC
LEVELDATAINDEX_INC = 1

.import level_definition_table
.import banktable
.import attackSound
.import hitSound
.import getHealthSound
.import getItemSound
.import getHurtSound
.import dieSound
.import haltmusic
.import title_music
.import font1
.import powerTable
.import levelString
.import livesString
.import gameOverString
.import titleDef
.import titlePalette
.import titleNametable

.endif
