.ifndef FLAGS_INC
FLAGS_INC = 1

;make sure to uncomment this before wrapping up any kind of release!
;it is only for convenience during beta testing!
LEVEL_SELECTOR_ENABLED = 1
MUSIC_ENABLE = 1
;DISPLAY_FRAME_CPU_USAGE = 1
;INVINCIBLE = 1
FADING_SPEED = 5

;warning: the exit entity is wider than 127 pixels, so using 8
;bit collisions will break it unless modified.
_16BIT_COLLISIONS = 1

.endif