;Meta Sprite Table
NomolosWalk0:
  .byte $08
  .byte $00,$00,$00,$00,$08
  .byte $00,$01,$00,$08,$00
  .byte $08,$18,$00,$00,$08
  .byte $08,$19,$00,$08,$00
  .byte $10,$2b,$02,$00,$08
  .byte $10,$2c,$02,$08,$00
  .byte $18,$3e,$02,$00,$08
  .byte $18,$3f,$02,$08,$00
NomolosWalk1:
  .byte $08
  .byte $00,$02,$00,$00,$08
  .byte $00,$03,$00,$08,$00
  .byte $08,$1a,$00,$00,$08
  .byte $08,$1b,$00,$08,$00
  .byte $10,$2d,$02,$00,$08
  .byte $10,$2e,$02,$08,$00
  .byte $18,$40,$02,$00,$08
  .byte $18,$41,$02,$08,$00
NomolosWalk2:
  .byte $08
  .byte $00,$05,$00,$00,$08
  .byte $00,$06,$00,$08,$00
  .byte $08,$1c,$00,$00,$08
  .byte $08,$1d,$00,$08,$00
  .byte $10,$2f,$02,$00,$08
  .byte $10,$30,$02,$08,$00
  .byte $18,$42,$02,$00,$08
  .byte $18,$43,$02,$08,$00
NomolosJump0:
  .byte $08
  .byte $00,$07,$00,$00,$08
  .byte $00,$08,$00,$08,$00
  .byte $08,$1e,$02,$00,$08
  .byte $08,$1f,$02,$08,$00
  .byte $10,$31,$02,$00,$08
  .byte $10,$32,$02,$08,$00
  .byte $18,$44,$02,$00,$08
  .byte $18,$45,$02,$08,$00
NomolosWalkOverlay0:
  .byte $04
  .byte $01,$0d,$01,$00,$08
  .byte $01,$0e,$01,$08,$00
  .byte $09,$24,$01,$00,$08
  .byte $09,$25,$01,$08,$00
NomolosWalkOverlay1:
  .byte $04
  .byte $01,$0f,$01,$00,$08
  .byte $01,$10,$01,$08,$00
  .byte $09,$26,$01,$00,$08
  .byte $09,$27,$01,$08,$00
NomolosWalkOverlay2:
  .byte $04
  .byte $01,$0f,$01,$00,$08
  .byte $01,$11,$01,$08,$00
  .byte $09,$26,$01,$00,$08
  .byte $09,$27,$01,$08,$00
NomolosJumpOverlay0:
  .byte $04
  .byte $01,$0d,$01,$00,$08
  .byte $01,$12,$01,$08,$00
  .byte $09,$24,$01,$00,$08
  .byte $09,$25,$01,$08,$00
Heart0:
  .byte $01
  .byte $00,$39,$01,$00,$00
Deentle0:
  .byte $04
  .byte $00,$4f,$02,$00,$08
  .byte $00,$50,$02,$08,$00
  .byte $08,$62,$02,$00,$08
  .byte $08,$63,$02,$08,$00
Deentle1:
  .byte $04
  .byte $00,$51,$02,$00,$08
  .byte $00,$52,$02,$08,$00
  .byte $08,$64,$02,$00,$08
  .byte $08,$65,$02,$08,$00
Explosion0:
  .byte $04
  .byte $00,$53,$00,$00,$08
  .byte $00,$54,$00,$08,$00
  .byte $08,$66,$00,$00,$08
  .byte $08,$67,$00,$08,$00
Explosion1:
  .byte $04
  .byte $00,$55,$00,$00,$08
  .byte $00,$56,$00,$08,$00
  .byte $08,$68,$00,$00,$08
  .byte $08,$69,$00,$08,$00
Explosion2:
  .byte $04
  .byte $00,$57,$00,$00,$08
  .byte $00,$58,$00,$08,$00
  .byte $08,$6a,$00,$00,$08
  .byte $08,$6b,$00,$08,$00
Mouse0:
  .byte $02
  .byte $00,$59,$02,$00,$08
  .byte $00,$5a,$02,$08,$00
SlumpedArmor0:
  .byte $06
  .byte $08,$6d,$00,$00,$08
  .byte $08,$6e,$00,$08,$00
  .byte $10,$7a,$02,$00,$08
  .byte $10,$7b,$02,$08,$00
  .byte $18,$86,$02,$00,$08
  .byte $18,$87,$02,$08,$00
SlumpedArmorOverlay0:
  .byte $02
  .byte $08,$6c,$01,$00,$00
  .byte $10,$79,$01,$00,$00
ScardyCat0:
  .byte $08
  .byte $00,$5b,$00,$00,$08
  .byte $00,$5c,$00,$08,$00
  .byte $08,$6f,$00,$00,$08
  .byte $08,$70,$00,$08,$00
  .byte $10,$7c,$00,$00,$08
  .byte $10,$7d,$00,$08,$00
  .byte $18,$88,$00,$00,$08
  .byte $18,$89,$00,$08,$00
ScardyCatOverlay0:
  .byte $04
  .byte $00,$71,$01,$00,$08
  .byte $00,$72,$01,$08,$00
  .byte $08,$7e,$01,$00,$08
  .byte $08,$7f,$01,$08,$00
NomolosFight0:
  .byte $0a
  .byte $f8,$4c,$00,$00,$08
  .byte $f8,$17,$00,$08,$00
  .byte $00,$5d,$00,$00,$08
  .byte $00,$5e,$00,$08,$00
  .byte $08,$73,$02,$00,$08
  .byte $08,$74,$00,$08,$00
  .byte $10,$80,$02,$00,$08
  .byte $10,$81,$02,$08,$00
  .byte $18,$8a,$02,$00,$08
  .byte $18,$8b,$02,$08,$00
NomolosFight1:
  .byte $10
  .byte $00,$5f,$00,$00,$08
  .byte $00,$60,$00,$08,$00
  .byte $00,$61,$00,$10,$f8
  .byte $00,$17,$00,$18,$f0
  .byte $08,$75,$02,$00,$08
  .byte $08,$76,$02,$08,$00
  .byte $08,$77,$00,$10,$f8
  .byte $08,$78,$00,$18,$f0
  .byte $10,$82,$02,$00,$08
  .byte $10,$83,$02,$08,$00
  .byte $10,$84,$00,$10,$f8
  .byte $10,$85,$00,$18,$f0
  .byte $18,$8c,$02,$00,$08
  .byte $18,$8d,$02,$08,$00
  .byte $18,$8e,$02,$10,$f8
  .byte $18,$17,$00,$18,$f0
NomolosFightOverlay0:
  .byte $04
  .byte $01,$13,$01,$00,$08
  .byte $01,$14,$01,$08,$00
  .byte $09,$17,$00,$00,$08
  .byte $09,$28,$01,$08,$00
NomolosFightOverlay1:
  .byte $04
  .byte $01,$15,$01,$00,$08
  .byte $01,$16,$01,$08,$00
  .byte $09,$29,$01,$00,$08
  .byte $09,$2a,$01,$08,$00
OneUp0:
  .byte $04
  .byte $00,$3d,$00,$00,$08
  .byte $00,$3d,$00,$08,$00
  .byte $08,$4d,$02,$00,$08
  .byte $08,$4e,$02,$08,$00
NomolosUseFlail0:
  .byte $0c
  .byte $00,$09,$02,$00,$08
  .byte $00,$0a,$00,$08,$00
  .byte $00,$0b,$00,$10,$f8
  .byte $08,$20,$02,$00,$08
  .byte $08,$21,$00,$08,$00
  .byte $08,$22,$00,$10,$f8
  .byte $10,$33,$02,$00,$08
  .byte $10,$34,$02,$08,$00
  .byte $10,$35,$02,$10,$f8
  .byte $18,$46,$02,$00,$08
  .byte $18,$47,$02,$08,$00
  .byte $18,$48,$02,$10,$f8
NomolosUseFlail1:
  .byte $0c
  .byte $00,$0c,$02,$00,$08
  .byte $00,$0a,$00,$08,$00
  .byte $00,$0b,$00,$10,$f8
  .byte $08,$23,$02,$00,$08
  .byte $08,$21,$00,$08,$00
  .byte $08,$22,$00,$10,$f8
  .byte $10,$36,$02,$00,$08
  .byte $10,$37,$02,$08,$00
  .byte $10,$38,$02,$10,$f8
  .byte $18,$49,$02,$00,$08
  .byte $18,$4a,$02,$08,$00
  .byte $18,$4b,$02,$10,$f8
FlailBall0:
  .byte $01
  .byte $f0,$3a,$02,$f0,$00
FlailBall1:
  .byte $01
  .byte $f0,$3a,$02,$00,$00
FlailBall2:
  .byte $01
  .byte $f0,$3a,$02,$10,$00
FlailBall3:
  .byte $01
  .byte $00,$3a,$02,$28,$00
FlailBall4:
  .byte $01
  .byte $10,$3a,$02,$10,$00
FlailBall5:
  .byte $01
  .byte $10,$3a,$02,$00,$00
FlailBall6:
  .byte $01
  .byte $10,$3a,$02,$f0,$00
FlailBall7:
  .byte $01
  .byte $00,$3a,$02,$d8,$00
NomolosFlailOverlay0:
  .byte $04
  .byte $01,$13,$01,$03,$05
  .byte $01,$14,$01,$0b,$fd
  .byte $09,$17,$00,$03,$05
  .byte $09,$28,$01,$0b,$fd

;Animations
NomolosWalk:
  .byte $0a
  .word NomolosWalk0
  .word NomolosWalk1
  .word NomolosWalk0
  .word NomolosWalk2
  .word $0000

NomolosJump:
  .byte $0a
  .word NomolosJump0
  .word $0000

NomolosWalkOverlay:
  .byte $0a
  .word NomolosWalkOverlay0
  .word NomolosWalkOverlay1
  .word NomolosWalkOverlay0
  .word NomolosWalkOverlay2
  .word $0000

NomolosJumpOverlay:
  .byte $0a
  .word NomolosJumpOverlay0
  .word $0000

Heart:
  .byte $0a
  .word Heart0
  .word $0000

DeentleWalk:
  .byte $0a
  .word Deentle0
  .word Deentle1
  .word $0000

Explosion:
  .byte $02
  .word Explosion0
  .word Explosion1
  .word Explosion2
  .word $0000

Mouse:
  .byte $0a
  .word Mouse0
  .word $0000

NomolosFight:
  .byte $06
  .word NomolosFight0
  .word NomolosFight1
  .word $0000

NomolosFightOverlay:
  .byte $06
  .word NomolosFightOverlay0
  .word NomolosFightOverlay1
  .word $0000

NomolosUseFlail:
  .byte $06
  .word NomolosUseFlail0
  .word NomolosUseFlail1
  .word $0000

FlailBall:
  .byte $0a
  .word FlailBall0
  .word FlailBall1
  .word FlailBall2
  .word FlailBall3
  .word FlailBall4
  .word FlailBall5
  .word FlailBall6
  .word FlailBall7
  .word $0000

NomolosFlailOverlay:
  .byte $06
  .word NomolosFlailOverlay0
  .word NomolosFlailOverlay0
  .word $0000

