.include "flags.inc"
.include "ram.inc"
.include "zp.inc"
.include "ram.inc"
.include "ppu.inc"
.include "map.inc"
.include "fixed_bank_data.inc"
.include "load_level_state.inc"
.include "geotests.inc"
.include "nomolos_logic.inc"
.include "entity.inc"
.include "camera.inc"
.include "sprite.inc"
.include "entities.inc"
.include "play_level_state.inc"
.include "soundengine.inc"
.include "sound_effects.inc"
.include "spritesheet_common.inc"
.include "spritesheet1.inc"
.include "spritesheet2.inc"

.segment "ROM14"
.include "spritesheet_common_patterns_source.inc"
.include "spritesheet1_patterns_source.inc"

.segment "ROM12"
.include "spritesheet_common_patterns_source.inc"
.include "spritesheet2_patterns_source.inc"

.segment "ROM13"
.include "spritesheet_common_sprites_source.inc"
.include "spritesheet_common_animations_source.inc"

.include "bat.inc"
.include "oneup.inc"
.include "exitentity.inc"
.include "setrightmostx.inc"
.include "mouse.inc"
.include "explosion.inc"
.include "explosionspawner.inc"
.include "spearitem.inc"
.include "flailitem.inc"
.include "restart.inc"

.include "spritesheet1_sprites_source.inc"
.include "spritesheet1_animations_source.inc"

.include "deentle.inc"
.include "beedie.inc"
.include "grank.inc"
.include "skelekin.inc"
.include "batree.inc"
.include "owl.inc"
.include "snuffer.inc"
.include "snail.inc"
.include "dragon.inc"
.include "iceball.inc"
.include "shark.inc"
.include "stalactite.inc"
.include "dragonboss.inc"
.include "grubselimboj.inc"
.include "bigfireball.inc"
.include "boulder.inc"

.segment "ROM11"

.include "spritesheet_common_sprites_source.inc"
.include "spritesheet_common_animations_source.inc"

.include "bat.inc"
.include "oneup.inc"
.include "exitentity.inc"
.include "setrightmostx.inc"
.include "mouse.inc"
.include "explosion.inc"
.include "explosionspawner.inc"
.include "spearitem.inc"
.include "flailitem.inc"
.include "restart.inc"

.include "spritesheet2_sprites_source.inc"
.include "spritesheet2_animations_source.inc"
.include "phoenix.inc"
.include "fireball.inc"
.include "snake.inc"
.include "fireguy.inc"
.include "thoguth.inc"
.include "fireballspawner.inc"
.include "lightningbolt.inc"
.include "statue.inc"
.include "raven.inc"
.include "sheep.inc"
.include "bee.inc"
.include "gort.inc"
.include "hippocritter.inc"
.include "armoredskelekin.inc"
.include "attacknid.inc"
.include "laser.inc"
.include "sneep.inc"
.include "feather.inc"
