.include "structs.inc"
.include "constants.inc"
.include "flags.inc"
.include "ram.inc"
.include "zp.inc"
.include "famitracker.inc"
.include "ram.inc"
.include "misc.inc"
.include "gameUIData.inc"
.include "loadLevelState.inc"
.include "geotests.inc"
.include "nomolosLogic.inc"
.include "entity.inc"
.include "camera.inc"
.include "sprite.inc"
.include "sound.inc"

.segment "ROM2"

.include "spritesheet1_sprites_source.inc"
.include "spritesheet1_animations_source.inc"

.include "oneup.inc"
.include "exitentity.inc"
.include "mouse.inc"
.include "explosion.inc"  
.include "deentle.inc"
.include "flailitem.inc"
  