.include "flags.inc"
.include "ram.inc"
.include "zp.inc"
.include "ram.inc"
.include "ppu.inc"
.include "map.inc"
.include "fixed_bank_data.inc"
.include "load_level_state.inc"
.include "geotests.inc"
.include "nomolos_logic.inc"
.include "entity.inc"
.include "camera.inc"
.include "sprite.inc"

.segment "ROM14"

.include "spritesheet_common_patterns_source.inc"

.segment "CODE"
.include "spritesheet_common_sprites_source.inc"
.include "spritesheet_common_animations_source.inc"